add a test for visible __libc_stack_end
git-svn-id: https://svn.r-project.org/R/trunk@38731 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -43044,6 +43044,70 @@ _ACEOF
   fi
 
 
+## check for visible __libc_stack_end on Linux
+case "${host_os}" in
+  linux*)
+    echo "$as_me:$LINENO: checking for visible __lib_stack_end" >&5
+echo $ECHO_N "checking for visible __lib_stack_end... $ECHO_C" >&6
+if test "${r_cv_libc_stack_end+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  r_cv_libc_stack_end=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include "confdefs.h"
+#include <stdlib.h>
+extern void * __libc_stack_end;
+
+int main () {
+    exit(0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  r_cv_libc_stack_end=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+r_cv_libc_stack_end=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $r_cv_libc_stack_end" >&5
+echo "${ECHO_T}$r_cv_libc_stack_end" >&6
+
+  if test "${r_cv_libc_stack_end}" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBC_STACK_END 1
+_ACEOF
+
+  fi
+esac
+
+AC
+
 ### * Miscellaneous.
 
 ## Printing.
@@ -43451,7 +43515,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:43454:" \
+echo "$as_me:43518:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
