remove reference to f2c in error message
git-svn-id: https://svn.r-project.org/R/trunk@44082 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2637,9 +2637,7 @@ if test "${want_R_framework}" != no; then
       ;;
   esac
 fi
-
-
-if test "x${want_R_framework}" = xyes; then
+ if test "x${want_R_framework}" = xyes; then
   WANT_R_FRAMEWORK_TRUE=
   WANT_R_FRAMEWORK_FALSE='#'
 else
@@ -2662,9 +2660,7 @@ else
   want_R_shlib="${want_R_framework}"
 fi
 
-
-
-if test "x${want_R_shlib}" = xyes; then
+ if test "x${want_R_shlib}" = xyes; then
   WANT_R_SHLIB_TRUE=
   WANT_R_SHLIB_FALSE='#'
 else
@@ -2687,9 +2683,7 @@ echo "$as_me: WARNING: --enable-R-static-lib conflicts with --enable-R-shlib and
     want_R_static=no
   fi
 fi
-
-
-if test "x${want_R_static}" = xyes; then
+ if test "x${want_R_static}" = xyes; then
   WANT_R_STATIC_TRUE=
   WANT_R_STATIC_FALSE='#'
 else
@@ -2721,9 +2715,7 @@ else
   use_maintainer_mode=no
 fi
 
-
-
-if test "x${use_maintainer_mode}" = xyes; then
+ if test "x${use_maintainer_mode}" = xyes; then
   MAINTAINER_MODE_TRUE=
   MAINTAINER_MODE_FALSE='#'
 else
@@ -2940,9 +2932,7 @@ fi
 ## [use_libtool="${withval}"],
 ## [use_libtool=yes])
 ## </FIXME>
-
-
-if test "x${use_libtool}" = xyes; then
+ if test "x${use_libtool}" = xyes; then
   USE_LIBTOOL_TRUE=
   USE_LIBTOOL_FALSE='#'
 else
@@ -6343,8 +6333,8 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 else
-  { { echo "$as_me:$LINENO: error: Neither an F77 compiler nor f2c found" >&5
-echo "$as_me: error: Neither an F77 compiler nor f2c found" >&2;}
+  { { echo "$as_me:$LINENO: error: No F77 compiler found" >&5
+echo "$as_me: error: No F77 compiler found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -8229,7 +8219,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8232 "configure"' > conftest.$ac_ext
+  echo '#line 8222 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10008,11 +9998,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10011: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10001: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10015: \$? = $ac_status" >&5
+   echo "$as_me:10005: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10298,11 +10288,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10301: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10291: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10305: \$? = $ac_status" >&5
+   echo "$as_me:10295: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10402,11 +10392,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10405: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10395: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10409: \$? = $ac_status" >&5
+   echo "$as_me:10399: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12751,7 +12741,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12754 "configure"
+#line 12744 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12851,7 +12841,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12854 "configure"
+#line 12844 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15271,11 +15261,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15274: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15264: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15278: \$? = $ac_status" >&5
+   echo "$as_me:15268: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15375,11 +15365,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15378: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15368: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15382: \$? = $ac_status" >&5
+   echo "$as_me:15372: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16937,11 +16927,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16940: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16930: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16944: \$? = $ac_status" >&5
+   echo "$as_me:16934: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17041,11 +17031,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17044: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17034: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17048: \$? = $ac_status" >&5
+   echo "$as_me:17038: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19228,11 +19218,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19231: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19221: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19235: \$? = $ac_status" >&5
+   echo "$as_me:19225: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19518,11 +19508,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19521: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19511: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19525: \$? = $ac_status" >&5
+   echo "$as_me:19515: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19622,11 +19612,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19625: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19615: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19629: \$? = $ac_status" >&5
+   echo "$as_me:19619: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22319,9 +22309,7 @@ fi
 
 
 
-
-
-if test "${cross_compiling}" = yes; then
+ if test "${cross_compiling}" = yes; then
   CROSS_COMPILING_TRUE=
   CROSS_COMPILING_FALSE='#'
 else
@@ -29012,7 +29000,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:29015: \"$ac_link\") >&5
+(eval echo $as_me:29003: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -29095,7 +29083,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:29098: \"$ac_link\") >&5
+(eval echo $as_me:29086: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -30171,9 +30159,7 @@ fi
 
 
 
-
-
-if test "x${HAVE_FORTRAN_DOUBLE_COMPLEX}" != x; then
+ if test "x${HAVE_FORTRAN_DOUBLE_COMPLEX}" != x; then
   COMPILE_FORTRAN_DOUBLE_COMPLEX_TRUE=
   COMPILE_FORTRAN_DOUBLE_COMPLEX_FALSE='#'
 else
@@ -33143,9 +33129,7 @@ else
   fi
 fi
 
-
-
-if test "x${dylib_undefined_allowed}" = xyes; then
+ if test "x${dylib_undefined_allowed}" = xyes; then
   DYLIB_UNDEFINED_ALLOWED_TRUE=
   DYLIB_UNDEFINED_ALLOWED_FALSE='#'
 else
@@ -33153,9 +33137,7 @@ else
   DYLIB_UNDEFINED_ALLOWED_FALSE=
 fi
 
-
-
-if test "x${is_cygwin}" = xyes; then
+ if test "x${is_cygwin}" = xyes; then
   BUILD_CYGWIN_TRUE=
   BUILD_CYGWIN_FALSE='#'
 else
@@ -33183,9 +33165,7 @@ cat >>confdefs.h <<_ACEOF
 #define SHLIB_EXT "${SHLIB_EXT}"
 _ACEOF
 
-
-
-if test "x${use_exportfiles}" = xyes; then
+ if test "x${use_exportfiles}" = xyes; then
   USE_EXPORTFILES_TRUE=
   USE_EXPORTFILES_FALSE='#'
 else
@@ -39531,9 +39511,7 @@ if test "${acx_blas_ok}" != "yes"; then
   esac
 fi
 
-
-
-if test "x${use_blas_shlib}" = xyes; then
+ if test "x${use_blas_shlib}" = xyes; then
   BLAS_SHLIB_TRUE=
   BLAS_SHLIB_FALSE='#'
 else
@@ -39659,9 +39637,7 @@ if test "${use_blas_shlib}" = yes; then
   BLAS_LIBS="-L\$(R_HOME)/lib\$(R_ARCH) -lRblas"
 fi
 
-
-
-if test "x${use_veclib_g95fix}" = xyes; then
+ if test "x${use_veclib_g95fix}" = xyes; then
   USE_VECLIB_G95FIX_TRUE=
   USE_VECLIB_G95FIX_FALSE='#'
 else
@@ -39669,9 +39645,7 @@ else
   USE_VECLIB_G95FIX_FALSE=
 fi
 
-
-
-if test "${acx_blas_ok}" = "yes"; then
+ if test "${acx_blas_ok}" = "yes"; then
   USE_EXTERNAL_BLAS_TRUE=
   USE_EXTERNAL_BLAS_FALSE='#'
 else
@@ -39967,9 +39941,7 @@ if test "${acx_lapack_ok}" != "yes"; then
   LAPACK_LIBS="-L\$(R_HOME)/lib\$(R_ARCH) -lRlapack"
 fi
 
-
-
-if test "${acx_lapack_ok}" = "yes"; then
+ if test "${acx_lapack_ok}" = "yes"; then
   USE_EXTERNAL_LAPACK_TRUE=
   USE_EXTERNAL_LAPACK_FALSE='#'
 else
@@ -43144,9 +43116,7 @@ _ACEOF
 
 fi
 
-
-
-if test "x${use_aqua}" = xyes; then
+ if test "x${use_aqua}" = xyes; then
   BUILD_AQUA_TRUE=
   BUILD_AQUA_FALSE='#'
 else
@@ -44710,9 +44680,7 @@ fi
 fi
 { echo "$as_me:$LINENO: result: $r_cv_xdr" >&5
 echo "${ECHO_T}$r_cv_xdr" >&6; }
-
-
-if test "x${r_cv_xdr}" = xno; then
+ if test "x${r_cv_xdr}" = xno; then
   BUILD_XDR_TRUE=
   BUILD_XDR_FALSE='#'
 else
@@ -45079,9 +45047,7 @@ fi
 echo "${ECHO_T}$r_cv_zlib_mmap" >&6; }
 
 fi
-
-
-if test "x${have_zlib}" = xno; then
+ if test "x${have_zlib}" = xno; then
   BUILD_ZLIB_TRUE=
   BUILD_ZLIB_FALSE='#'
 else
@@ -45089,9 +45055,7 @@ else
   BUILD_ZLIB_FALSE=
 fi
 
-
-
-if test "x${have_zlib}" = xno && test "x${r_cv_zlib_mmap}" = xyes; then
+ if test "x${have_zlib}" = xno && test "x${r_cv_zlib_mmap}" = xyes; then
   USE_MMAP_ZLIB_TRUE=
   USE_MMAP_ZLIB_FALSE='#'
 else
@@ -45330,9 +45294,7 @@ else
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 fi
-
-
-if test "x${have_bzlib}" = xno; then
+ if test "x${have_bzlib}" = xno; then
   BUILD_BZLIB_TRUE=
   BUILD_BZLIB_FALSE='#'
 else
@@ -45655,9 +45617,7 @@ else
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 fi
-
-
-if test "x${r_have_pcre4}" != xyes; then
+ if test "x${r_have_pcre4}" != xyes; then
   BUILD_PCRE_TRUE=
   BUILD_PCRE_FALSE='#'
 else
@@ -46902,9 +46862,7 @@ echo "${ECHO_T}$r_cv_javac14_works" >&6; }
 if test "${r_cv_javac14_works}" = yes; then
   JAVAC14="${JAVAC} -source 1.4 -target 1.4"
 fi
-
-
-if test "x${r_cv_javac14_works}" = xyes; then
+ if test "x${r_cv_javac14_works}" = xyes; then
   BUILD_JAVA14_TRUE=
   BUILD_JAVA14_FALSE='#'
 else
@@ -47893,9 +47851,7 @@ echo "$as_me: error: Some of the recommended packages are missing
 fi
 
 fi
-
-
-if test "x${use_recommended_packages}" = xyes; then
+ if test "x${use_recommended_packages}" = xyes; then
   USE_RECOMMENDED_PACKAGES_TRUE=
   USE_RECOMMENDED_PACKAGES_FALSE='#'
 else
@@ -47952,38 +47908,53 @@ echo "${ECHO_T}no" >&6; }
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
-if mkdir -p --version . >/dev/null 2>&1 && test ! -d ./--version; then
-  # We used to keeping the `.' as first argument, in order to
-  # allow $(mkdir_p) to be used without argument.  As in
-  #   $(mkdir_p) $(somedir)
-  # where $(somedir) is conditionally defined.  However this is wrong
-  # for two reasons:
-  #  1. if the package is installed by a user who cannot write `.'
-  #     make install will fail,
-  #  2. the above comment should most certainly read
-  #     $(mkdir_p) $(DESTDIR)$(somedir)
-  #     so it does not work when $(somedir) is undefined and
-  #     $(DESTDIR) is not.
-  #  To support the latter case, we have to write
-  #     test -z "$(somedir)" || $(mkdir_p) $(DESTDIR)$(somedir),
-  #  so the `.' trick is pointless.
-  mkdir_p='mkdir -p --'
+{ echo "$as_me:$LINENO: checking for a thread-safe mkdir -p" >&5
+echo $ECHO_N "checking for a thread-safe mkdir -p... $ECHO_C" >&6; }
+if test -z "$MKDIR_P"; then
+  if test "${ac_cv_path_mkdir+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  # On NextStep and OpenStep, the `mkdir' command does not
-  # recognize any option.  It will interpret all options as
-  # directories to create, and then abort because `.' already
-  # exists.
-  for d in ./-p ./--version;
-  do
-    test -d $d && rmdir $d
-  done
-  # $(mkinstalldirs) is defined by Automake if mkinstalldirs exists.
-  if test -f "$ac_aux_dir/mkinstalldirs"; then
-    mkdir_p='$(mkinstalldirs)'
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH$PATH_SEPARATOR/opt/sfw/bin
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_prog in mkdir gmkdir; do
+	 for ac_exec_ext in '' $ac_executable_extensions; do
+	   { test -f "$as_dir/$ac_prog$ac_exec_ext" && $as_test_x "$as_dir/$ac_prog$ac_exec_ext"; } || continue
+	   case `"$as_dir/$ac_prog$ac_exec_ext" --version 2>&1` in #(
+	     'mkdir (GNU coreutils) '* | \
+	     'mkdir (coreutils) '* | \
+	     'mkdir (fileutils) '4.1*)
+	       ac_cv_path_mkdir=$as_dir/$ac_prog$ac_exec_ext
+	       break 3;;
+	   esac
+	 done
+       done
+done
+IFS=$as_save_IFS
+
+fi
+
+  if test "${ac_cv_path_mkdir+set}" = set; then
+    MKDIR_P="$ac_cv_path_mkdir -p"
   else
-    mkdir_p='$(install_sh) -d'
+    # As a last resort, use the slow shell script.  Don't cache a
+    # value for MKDIR_P within a source directory, because that will
+    # break other packages using the cache if that directory is
+    # removed, or if the value is a relative name.
+    test -d ./--version && rmdir ./--version
+    MKDIR_P="$ac_install_sh -d"
   fi
 fi
+{ echo "$as_me:$LINENO: result: $MKDIR_P" >&5
+echo "${ECHO_T}$MKDIR_P" >&6; }
+
+mkdir_p="$MKDIR_P"
+case $mkdir_p in
+  [\\/$]* | ?:[\\/]*) ;;
+  */*) mkdir_p="\$(top_builddir)/$mkdir_p" ;;
+esac
 
 
 
@@ -55930,9 +55901,7 @@ _ACEOF
 fi
 
 
-
-
-if test "x${USE_NLS}" = xyes; then
+ if test "x${USE_NLS}" = xyes; then
   USE_NLS_TRUE=
   USE_NLS_FALSE='#'
 else
@@ -55940,9 +55909,7 @@ else
   USE_NLS_FALSE=
 fi
 
-
-
-if test "x${USE_INCLUDED_LIBINTL}" = xyes; then
+ if test "x${USE_INCLUDED_LIBINTL}" = xyes; then
   BUILD_LIBINTL_TRUE=
   BUILD_LIBINTL_FALSE='#'
 else
@@ -56668,6 +56635,7 @@ gives unlimited permission to copy, distribute and modify it."
 ac_pwd='$ac_pwd'
 srcdir='$srcdir'
 INSTALL='$INSTALL'
+MKDIR_P='$MKDIR_P'
 _ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
@@ -57606,6 +57574,11 @@ ac_abs_srcdir=$ac_abs_top_srcdir$ac_dir_suffix
   [\\/$]* | ?:[\\/]* ) ac_INSTALL=$INSTALL ;;
   *) ac_INSTALL=$ac_top_build_prefix$INSTALL ;;
   esac
+  ac_MKDIR_P=$MKDIR_P
+  case $MKDIR_P in
+  [\\/$]* | ?:[\\/]* ) ;;
+  */*) ac_MKDIR_P=$ac_top_build_prefix$MKDIR_P ;;
+  esac
 _ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
@@ -57659,6 +57632,7 @@ s&@builddir@&$ac_builddir&;t t
 s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
+s&@MKDIR_P@&$ac_MKDIR_P&;t t
 $ac_datarootdir_hack
 " $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" | sed -f "$tmp/subs-4.sed" >$tmp/out
 
