port improved __NO_MATH_INLINES check from trunk
git-svn-id: https://svn.r-project.org/R/branches/R-2-0-patches@31595 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27068,20 +27068,62 @@ fi
 
 case "${host_cpu}" in
   i*86)
-    cat >conftest.$ac_ext <<_ACEOF
+    echo "$as_me:$LINENO: checking whether C runtime needs -D__NO_MATH_INLINES" >&5
+echo $ECHO_N "checking whether C runtime needs -D__NO_MATH_INLINES... $ECHO_C" >&6
+if test "${r_cv_c_no_math_inlines+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  r_cv_c_no_math_inlines=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
+
 #include <math.h>
 #if defined(__GLIBC__)
-  yes
+int main () {
+  double x, y;
+  x = -0./1.;
+  y = exp(x);
+  exit (y != 0.);
+}
+#else
+int main () {
+  exit(0);
+}
 #endif
 
 _ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  $EGREP "yes" >/dev/null 2>&1; then
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  r_cv_c_no_math_inlines=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+r_cv_c_no_math_inlines=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $r_cv_c_no_math_inlines" >&5
+echo "${ECHO_T}$r_cv_c_no_math_inlines" >&6
+if test "${r_cv_c_no_math_inlines}" = yes; then
   separator=""
 test -z "${separator}" && separator=" "
 if test -z "${R_XTRA_CFLAGS}"; then
@@ -27090,8 +27132,6 @@ else
   R_XTRA_CFLAGS="${R_XTRA_CFLAGS}${separator}-D__NO_MATH_INLINES"
 fi
 fi
-rm -f conftest*
-
 
     ## We used to add -mieee-fp here, but it seems it is really a
     ## gcc linker flag for old Linuxen adding -lieee to a non-shared link.
