make --with-ICU the default report on R_SHELL clean up output from ObjC++ search
git-svn-id: https://svn.r-project.org/R/trunk@47356 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1796,7 +1796,7 @@ Optional Packages:
   --with-recommended-packages
                           use/install recommended R packages [yes]
   --with-iconv            use iconv library [yes]
-  --with-ICU              use ICU library [no]
+  --with-ICU              use ICU library [yes]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
@@ -3005,7 +3005,7 @@ else
 fi
 
 else
-  use_ICU=no
+  use_ICU=yes
 fi
 
 
@@ -7523,19 +7523,15 @@ fi
 
 
 
-r_cached_objcxx=yes
-{ echo "$as_me:$LINENO: checking for cached ObjC++ compiler" >&5
-echo $ECHO_N "checking for cached ObjC++ compiler... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking for Objective C++ compiler" >&5
+echo $ECHO_N "checking for Objective C++ compiler... $ECHO_C" >&6; }
 if test "${r_cv_OBJCXX+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
- { echo "$as_me:$LINENO: result: none" >&5
-echo "${ECHO_T}none" >&6; }
- r_cached_objcxx=no
+{ echo "$as_me:$LINENO: result: trying some possibilities" >&5
+echo "${ECHO_T}trying some possibilities" >&6; }
 if test -n "${OBJCXX}"; then
-  { echo "$as_me:$LINENO: result: defining OBJCXX to be ${OBJCXX}" >&5
-echo "${ECHO_T}defining OBJCXX to be ${OBJCXX}" >&6; }
   { echo "$as_me:$LINENO: checking whether ${OBJCXX} can compile ObjC++" >&5
 echo $ECHO_N "checking whether ${OBJCXX} can compile ObjC++... $ECHO_C" >&6; }
 cat << \EOF > conftest.mm
@@ -7647,8 +7643,11 @@ fi
 fi
 
 fi
-{ echo "$as_me:$LINENO: checking for Objective C++ compiler" >&5
-echo $ECHO_N "checking for Objective C++ compiler... $ECHO_C" >&6; }
+r_cv_OBJCXX="${OBJCXX}"
+
+fi
+
+OBJCXX="${r_cv_OBJCXX}"
 if test -z "${OBJCXX}"; then
   { echo "$as_me:$LINENO: result: no working compiler found" >&5
 echo "${ECHO_T}no working compiler found" >&6; }
@@ -7656,15 +7655,6 @@ else
   { echo "$as_me:$LINENO: result: ${OBJCXX}" >&5
 echo "${ECHO_T}${OBJCXX}" >&6; }
 fi
-r_cv_OBJCXX="${OBJCXX}"
-if test "${r_cached_objcxx}" = yes; then
-  { echo "$as_me:$LINENO: result: \"${r_cv_OBJCXX}\"" >&5
-echo "${ECHO_T}\"${r_cv_OBJCXX}\"" >&6; }
-fi
-
-fi
-
-OBJCXX="${r_cv_OBJCXX}"
 
 
 
@@ -8222,13 +8212,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:8225: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:8215: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:8228: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:8218: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:8231: output\"" >&5)
+  (eval echo "\"\$as_me:8221: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -9438,7 +9428,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 9441 "configure"' > conftest.$ac_ext
+  echo '#line 9431 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11889,11 +11879,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11892: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11882: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11896: \$? = $ac_status" >&5
+   echo "$as_me:11886: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12228,11 +12218,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12231: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12221: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12235: \$? = $ac_status" >&5
+   echo "$as_me:12225: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12333,11 +12323,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12336: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12326: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12340: \$? = $ac_status" >&5
+   echo "$as_me:12330: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12388,11 +12378,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12391: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12381: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12395: \$? = $ac_status" >&5
+   echo "$as_me:12385: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15144,7 +15134,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 15147 "configure"
+#line 15137 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15240,7 +15230,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 15243 "configure"
+#line 15233 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17252,11 +17242,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17255: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17245: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17259: \$? = $ac_status" >&5
+   echo "$as_me:17249: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17351,11 +17341,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17354: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17344: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17358: \$? = $ac_status" >&5
+   echo "$as_me:17348: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17403,11 +17393,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17406: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17396: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17410: \$? = $ac_status" >&5
+   echo "$as_me:17400: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18811,11 +18801,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18814: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18804: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18818: \$? = $ac_status" >&5
+   echo "$as_me:18808: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18910,11 +18900,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18913: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18903: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18917: \$? = $ac_status" >&5
+   echo "$as_me:18907: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18962,11 +18952,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18965: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18955: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18969: \$? = $ac_status" >&5
+   echo "$as_me:18959: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27671,7 +27661,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:27674: \"$ac_link\") >&5
+(eval echo $as_me:27664: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -27754,7 +27744,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:27757: \"$ac_link\") >&5
+(eval echo $as_me:27747: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -39693,8 +39683,92 @@ fi
 
 ## support for ICU
 if test "$use_ICU" = yes ; then
-case "${host_os}" in
-  darwin*)
+  { echo "$as_me:$LINENO: checking for ICU" >&5
+echo $ECHO_N "checking for ICU... $ECHO_C" >&6; }
+if test "${r_cv_icu+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  r_save_LIBS="${LIBS}"
+LIBS="${LIBS} -licuuc -licui18n"
+if test "$cross_compiling" = yes; then
+  r_cv_icu=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <unicode/utypes.h>
+#include <unicode/ucol.h>
+#include <unicode/uloc.h>
+#include <unicode/uiter.h>
+
+#include <stdlib.h>
+
+int main () {
+    UErrorCode  status = U_ZERO_ERROR;
+    UCollator *collator;
+    collator = ucol_open(NULL, &status);
+    if (U_FAILURE(status))  exit(1);
+    exit(0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  r_cv_icu=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+r_cv_icu=no
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+LIBS="${r_save_LIBS}"
+
+fi
+{ echo "$as_me:$LINENO: result: $r_cv_icu" >&5
+echo "${ECHO_T}$r_cv_icu" >&6; }
+if test "x${r_cv_icu}" = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_ICU 1
+_ACEOF
+
+  LIBS="${LIBS} -licuuc -licui18n"
+else
+  use_ICU=no
+fi
+
+  if test "$use_ICU" = no ; then
+    case "${host_os}" in
+      ## darwin has ICU 3.2 in 10.4, 3.6 in 10.5
+      darwin*)
 
 { echo "$as_me:$LINENO: checking for ucol_open in -licucore" >&5
 echo $ECHO_N "checking for ucol_open in -licucore... $ECHO_C" >&6; }
@@ -39788,91 +39862,10 @@ cat >>confdefs.h <<\_ACEOF
 #define USE_ICU 1
 _ACEOF
 
-  ;;
-  *)
-    { echo "$as_me:$LINENO: checking for ICU" >&5
-echo $ECHO_N "checking for ICU... $ECHO_C" >&6; }
-if test "${r_cv_icu+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  r_save_LIBS="${LIBS}"
-LIBS="${LIBS} -licuuc -licui18n"
-if test "$cross_compiling" = yes; then
-  r_cv_icu=no
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-#include <unicode/utypes.h>
-#include <unicode/ucol.h>
-#include <unicode/uloc.h>
-#include <unicode/uiter.h>
-
-#include <stdlib.h>
-
-int main () {
-    UErrorCode  status = U_ZERO_ERROR;
-    UCollator *collator;
-    collator = ucol_open(NULL, &status);
-    if (U_FAILURE(status))  exit(1);
-    exit(0);
-}
-
-_ACEOF
-rm -f conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_try") 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  r_cv_icu=yes
-else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-( exit $ac_status )
-r_cv_icu=no
-fi
-rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-
-
-LIBS="${r_save_LIBS}"
-
-fi
-{ echo "$as_me:$LINENO: result: $r_cv_icu" >&5
-echo "${ECHO_T}$r_cv_icu" >&6; }
-if test "x${r_cv_icu}" = xyes; then
-
-cat >>confdefs.h <<\_ACEOF
-#define USE_ICU 1
-_ACEOF
-
-  LIBS="${LIBS} -licuuc -licui18n"
-else
-  use_ICU=no
-fi
-
-  esac
+	use_ICU=yes
+      ;;
+    esac
+  fi
 fi
 
 
@@ -48052,11 +48045,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48055: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48048: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:48059: \$? = $ac_status" >&5
+   echo "$as_me:48052: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -48151,11 +48144,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48154: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48147: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48158: \$? = $ac_status" >&5
+   echo "$as_me:48151: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -48203,11 +48196,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48206: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48199: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48210: \$? = $ac_status" >&5
+   echo "$as_me:48203: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -58330,6 +58323,8 @@ esac
 ### since some AIX systems have zsh as sh.
 : ${R_SHELL=${SHELL}}
 
+{ echo "$as_me:$LINENO: result: using as R_SHELL for scripts ... ${R_SHELL}" >&5
+echo "${ECHO_T}using as R_SHELL for scripts ... ${R_SHELL}" >&6; }
 
 
 ### * Win32 overrides
