use run-time linking on AIX and no export files
git-svn-id: https://svn.r-project.org/R/trunk@38785 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29622,7 +29622,7 @@ fi
 ## user did not provide defaults, an error results.  A warning is given
 ## if nothing was obtained for SHLIB_CXXLDFLAGS.
 ##
-## Note also that some systems (notably AIX) do not allow for unresolved
+## Note also that some systems (formerly AIX) do not allow for unresolved
 ## symbols at link time.  For such systems, we link against -lm (in case
 ## it exists) when building a shlib module via SHLIB_LIBADD.
 
@@ -29746,15 +29746,27 @@ fi
 ## Step 3.  Individual platform overrides.
 dylib_undefined_allowed=yes
 case "${host_os}" in
+  aix123*|aix4.01*)
+    ## These need a form of linking we no longer support
+    { { echo "$as_me:$LINENO: error: AIX prior to 4.2 is not supported" >&5
+echo "$as_me: error: AIX prior to 4.2 is not supported" >&2;}
+   { (exit 1); exit 1; }; }
+    ;;
   aix*)
-    use_exportfiles=yes
+    ## now use run-time linking
+    # use_exportfiles=yes
     ## All AIX code is PIC.
     cpicflags=
     cxxpicflags=
     fpicflags=
+    ## not clear if this is correct for native compilers
     wl="-Wl,"
-    main_ldflags="${wl}-bdynamic ${wl}-bE:\$(top_builddir)/etc/R.exp ${wl}-bM:SRE"
-    shlib_ldflags="${wl}-bM:SRE ${wl}-H512 ${wl}-T512 ${wl}-bnoentry ${wl}-bexpall ${wl}-bI:\$(R_HOME)/etc/R.exp"
+    ## libtool suggests that ia64 needs -Bexport and not -brtl
+    ## but we have no confirmation.
+    main_ldflags="${wl}-brtl ${wl}-bexpall"
+    shlib_ldflags="${wl}-G ${wl}-bexpall ${wl}-bnoentry"
+#    main_ldflags="${wl}-bdynamic ${wl}-bE:\$(top_builddir)/etc/R.exp ${wl}-bM:SRE"
+#    shlib_ldflags="${wl}-bM:SRE ${wl}-H512 ${wl}-T512 ${wl}-bnoentry ${wl}-bexpall ${wl}-bI:\$(R_HOME)/etc/R.exp"
     SHLIB_LIBADD="\$(LIBM)"
     ;;
   darwin*)
@@ -29915,6 +29927,7 @@ fi ;;
     fi
     ;;
   openbsd*)
+    ## looks like ${wl} is not defined here.  Perhaps in libtool code?
     if test -z "`echo __ELF__ | $CC -E - | grep __ELF__`"; then
       main_ldflags="${wl}-export-dynamic"
       shlib_ldflags="-shared -fPIC"
@@ -30077,9 +30090,9 @@ RLAPACK_LDFLAGS=""
 RBLAS_LDFLAGS=""
 case "${host_os}" in
   aix*)
-    ## Pure guesswork so far
-    RLAPACK_LDFLAGS="${wl}-bE:\$(top_builddir)/etc/Rlapack.exp"
-    LAPACK_LDFLAGS="${wl}-bI:\$(R_HOME)/etc/Rlapack.exp"
+    ## Not needed for -brtl linking
+    # RLAPACK_LDFLAGS="${wl}-bE:\$(top_builddir)/etc/Rlapack.exp"
+    # LAPACK_LDFLAGS="${wl}-bI:\$(R_HOME)/etc/Rlapack.exp"
     ;;
   darwin*)
     DYLIB_EXT=".dylib"
@@ -43602,7 +43615,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:43605:" \
+echo "$as_me:43618:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
