update to 44446
git-svn-id: https://svn.r-project.org/R/branches/R-Cairo@44447 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2647,7 +2647,9 @@ if test "${want_R_framework}" != no; then
       ;;
   esac
 fi
- if test "x${want_R_framework}" = xyes; then
+
+
+if test "x${want_R_framework}" = xyes; then
   WANT_R_FRAMEWORK_TRUE=
   WANT_R_FRAMEWORK_FALSE='#'
 else
@@ -2670,7 +2672,9 @@ else
   want_R_shlib="${want_R_framework}"
 fi
 
- if test "x${want_R_shlib}" = xyes; then
+
+
+if test "x${want_R_shlib}" = xyes; then
   WANT_R_SHLIB_TRUE=
   WANT_R_SHLIB_FALSE='#'
 else
@@ -2693,7 +2697,9 @@ echo "$as_me: WARNING: --enable-R-static-lib conflicts with --enable-R-shlib and
     want_R_static=no
   fi
 fi
- if test "x${want_R_static}" = xyes; then
+
+
+if test "x${want_R_static}" = xyes; then
   WANT_R_STATIC_TRUE=
   WANT_R_STATIC_FALSE='#'
 else
@@ -2725,7 +2731,9 @@ else
   use_maintainer_mode=no
 fi
 
- if test "x${use_maintainer_mode}" = xyes; then
+
+
+if test "x${use_maintainer_mode}" = xyes; then
   MAINTAINER_MODE_TRUE=
   MAINTAINER_MODE_FALSE='#'
 else
@@ -2942,7 +2950,9 @@ fi
 ## [use_libtool="${withval}"],
 ## [use_libtool=yes])
 ## </FIXME>
- if test "x${use_libtool}" = xyes; then
+
+
+if test "x${use_libtool}" = xyes; then
   USE_LIBTOOL_TRUE=
   USE_LIBTOOL_FALSE='#'
 else
@@ -4428,7 +4438,7 @@ test -n "$R_GZIPCMD" || R_GZIPCMD="true"
 
 ## Browser
 if test -z "${R_BROWSER}"; then
-  for ac_prog in firefox mozilla galeon kfmclient opera gnome-moz-remote open
+  for ac_prog in firefox mozilla galeon opera xdg-open kfmclient gnome-moz-remote open
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -8272,7 +8282,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8275 "configure"' > conftest.$ac_ext
+  echo '#line 8285 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10366,11 +10376,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10369: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10379: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10373: \$? = $ac_status" >&5
+   echo "$as_me:10383: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10656,11 +10666,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10659: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10669: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10663: \$? = $ac_status" >&5
+   echo "$as_me:10673: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10760,11 +10770,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10763: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10773: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10767: \$? = $ac_status" >&5
+   echo "$as_me:10777: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13124,7 +13134,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13127 "configure"
+#line 13137 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13224,7 +13234,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13227 "configure"
+#line 13237 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15625,11 +15635,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15628: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15638: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15632: \$? = $ac_status" >&5
+   echo "$as_me:15642: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15729,11 +15739,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15732: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15742: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15736: \$? = $ac_status" >&5
+   echo "$as_me:15746: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17312,11 +17322,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17325: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17319: \$? = $ac_status" >&5
+   echo "$as_me:17329: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17416,11 +17426,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17419: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17429: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17423: \$? = $ac_status" >&5
+   echo "$as_me:17433: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19623,11 +19633,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19626: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19636: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19630: \$? = $ac_status" >&5
+   echo "$as_me:19640: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19913,11 +19923,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19916: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19926: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19920: \$? = $ac_status" >&5
+   echo "$as_me:19930: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20017,11 +20027,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20020: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20030: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20024: \$? = $ac_status" >&5
+   echo "$as_me:20034: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22739,7 +22749,9 @@ fi
 
 
 
- if test "${cross_compiling}" = yes; then
+
+
+if test "${cross_compiling}" = yes; then
   CROSS_COMPILING_TRUE=
   CROSS_COMPILING_FALSE='#'
 else
@@ -29430,7 +29442,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:29433: \"$ac_link\") >&5
+(eval echo $as_me:29445: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -29513,7 +29525,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:29516: \"$ac_link\") >&5
+(eval echo $as_me:29528: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -30589,7 +30601,9 @@ fi
 
 
 
- if test "x${HAVE_FORTRAN_DOUBLE_COMPLEX}" != x; then
+
+
+if test "x${HAVE_FORTRAN_DOUBLE_COMPLEX}" != x; then
   COMPILE_FORTRAN_DOUBLE_COMPLEX_TRUE=
   COMPILE_FORTRAN_DOUBLE_COMPLEX_FALSE='#'
 else
@@ -33559,7 +33573,9 @@ else
   fi
 fi
 
- if test "x${dylib_undefined_allowed}" = xyes; then
+
+
+if test "x${dylib_undefined_allowed}" = xyes; then
   DYLIB_UNDEFINED_ALLOWED_TRUE=
   DYLIB_UNDEFINED_ALLOWED_FALSE='#'
 else
@@ -33567,7 +33583,9 @@ else
   DYLIB_UNDEFINED_ALLOWED_FALSE=
 fi
 
- if test "x${is_cygwin}" = xyes; then
+
+
+if test "x${is_cygwin}" = xyes; then
   BUILD_CYGWIN_TRUE=
   BUILD_CYGWIN_FALSE='#'
 else
@@ -33595,7 +33613,9 @@ cat >>confdefs.h <<_ACEOF
 #define SHLIB_EXT "${SHLIB_EXT}"
 _ACEOF
 
- if test "x${use_exportfiles}" = xyes; then
+
+
+if test "x${use_exportfiles}" = xyes; then
   USE_EXPORTFILES_TRUE=
   USE_EXPORTFILES_FALSE='#'
 else
@@ -39941,7 +39961,9 @@ if test "${acx_blas_ok}" != "yes"; then
   esac
 fi
 
- if test "x${use_blas_shlib}" = xyes; then
+
+
+if test "x${use_blas_shlib}" = xyes; then
   BLAS_SHLIB_TRUE=
   BLAS_SHLIB_FALSE='#'
 else
@@ -40067,7 +40089,9 @@ if test "${use_blas_shlib}" = yes; then
   BLAS_LIBS="-L\$(R_HOME)/lib\$(R_ARCH) -lRblas"
 fi
 
- if test "x${use_veclib_g95fix}" = xyes; then
+
+
+if test "x${use_veclib_g95fix}" = xyes; then
   USE_VECLIB_G95FIX_TRUE=
   USE_VECLIB_G95FIX_FALSE='#'
 else
@@ -40075,7 +40099,9 @@ else
   USE_VECLIB_G95FIX_FALSE=
 fi
 
- if test "${acx_blas_ok}" = "yes"; then
+
+
+if test "${acx_blas_ok}" = "yes"; then
   USE_EXTERNAL_BLAS_TRUE=
   USE_EXTERNAL_BLAS_FALSE='#'
 else
@@ -40371,7 +40397,9 @@ if test "${acx_lapack_ok}" != "yes"; then
   LAPACK_LIBS="-L\$(R_HOME)/lib\$(R_ARCH) -lRlapack"
 fi
 
- if test "${acx_lapack_ok}" = "yes"; then
+
+
+if test "${acx_lapack_ok}" = "yes"; then
   USE_EXTERNAL_LAPACK_TRUE=
   USE_EXTERNAL_LAPACK_FALSE='#'
 else
@@ -43683,7 +43711,9 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
- if test "x${r_cv_cairo_works}" = xyes; then
+
+
+if test "x${r_cv_cairo_works}" = xyes; then
   BUILD_WITH_CAIRO_TRUE=
   BUILD_WITH_CAIRO_FALSE='#'
 else
@@ -43802,7 +43832,9 @@ _ACEOF
 
 fi
 
- if test "x${use_aqua}" = xyes; then
+
+
+if test "x${use_aqua}" = xyes; then
   BUILD_AQUA_TRUE=
   BUILD_AQUA_FALSE='#'
 else
@@ -45366,7 +45398,9 @@ fi
 fi
 { echo "$as_me:$LINENO: result: $r_cv_xdr" >&5
 echo "${ECHO_T}$r_cv_xdr" >&6; }
- if test "x${r_cv_xdr}" = xno; then
+
+
+if test "x${r_cv_xdr}" = xno; then
   BUILD_XDR_TRUE=
   BUILD_XDR_FALSE='#'
 else
@@ -45733,7 +45767,9 @@ fi
 echo "${ECHO_T}$r_cv_zlib_mmap" >&6; }
 
 fi
- if test "x${have_zlib}" = xno; then
+
+
+if test "x${have_zlib}" = xno; then
   BUILD_ZLIB_TRUE=
   BUILD_ZLIB_FALSE='#'
 else
@@ -45741,7 +45777,9 @@ else
   BUILD_ZLIB_FALSE=
 fi
 
- if test "x${have_zlib}" = xno && test "x${r_cv_zlib_mmap}" = xyes; then
+
+
+if test "x${have_zlib}" = xno && test "x${r_cv_zlib_mmap}" = xyes; then
   USE_MMAP_ZLIB_TRUE=
   USE_MMAP_ZLIB_FALSE='#'
 else
@@ -45980,7 +46018,9 @@ else
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 fi
- if test "x${have_bzlib}" = xno; then
+
+
+if test "x${have_bzlib}" = xno; then
   BUILD_BZLIB_TRUE=
   BUILD_BZLIB_FALSE='#'
 else
@@ -46303,7 +46343,9 @@ else
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 fi
- if test "x${r_have_pcre4}" != xyes; then
+
+
+if test "x${r_have_pcre4}" != xyes; then
   BUILD_PCRE_TRUE=
   BUILD_PCRE_FALSE='#'
 else
@@ -47548,7 +47590,9 @@ echo "${ECHO_T}$r_cv_javac14_works" >&6; }
 if test "${r_cv_javac14_works}" = yes; then
   JAVAC14="${JAVAC} -source 1.4 -target 1.4"
 fi
- if test "x${r_cv_javac14_works}" = xyes; then
+
+
+if test "x${r_cv_javac14_works}" = xyes; then
   BUILD_JAVA14_TRUE=
   BUILD_JAVA14_FALSE='#'
 else
@@ -48537,7 +48581,9 @@ echo "$as_me: error: Some of the recommended packages are missing
 fi
 
 fi
- if test "x${use_recommended_packages}" = xyes; then
+
+
+if test "x${use_recommended_packages}" = xyes; then
   USE_RECOMMENDED_PACKAGES_TRUE=
   USE_RECOMMENDED_PACKAGES_FALSE='#'
 else
@@ -48594,53 +48640,38 @@ echo "${ECHO_T}no" >&6; }
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
-{ echo "$as_me:$LINENO: checking for a thread-safe mkdir -p" >&5
-echo $ECHO_N "checking for a thread-safe mkdir -p... $ECHO_C" >&6; }
-if test -z "$MKDIR_P"; then
-  if test "${ac_cv_path_mkdir+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
+if mkdir -p --version . >/dev/null 2>&1 && test ! -d ./--version; then
+  # We used to keeping the `.' as first argument, in order to
+  # allow $(mkdir_p) to be used without argument.  As in
+  #   $(mkdir_p) $(somedir)
+  # where $(somedir) is conditionally defined.  However this is wrong
+  # for two reasons:
+  #  1. if the package is installed by a user who cannot write `.'
+  #     make install will fail,
+  #  2. the above comment should most certainly read
+  #     $(mkdir_p) $(DESTDIR)$(somedir)
+  #     so it does not work when $(somedir) is undefined and
+  #     $(DESTDIR) is not.
+  #  To support the latter case, we have to write
+  #     test -z "$(somedir)" || $(mkdir_p) $(DESTDIR)$(somedir),
+  #  so the `.' trick is pointless.
+  mkdir_p='mkdir -p --'
 else
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH$PATH_SEPARATOR/opt/sfw/bin
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_prog in mkdir gmkdir; do
-	 for ac_exec_ext in '' $ac_executable_extensions; do
-	   { test -f "$as_dir/$ac_prog$ac_exec_ext" && $as_test_x "$as_dir/$ac_prog$ac_exec_ext"; } || continue
-	   case `"$as_dir/$ac_prog$ac_exec_ext" --version 2>&1` in #(
-	     'mkdir (GNU coreutils) '* | \
-	     'mkdir (coreutils) '* | \
-	     'mkdir (fileutils) '4.1*)
-	       ac_cv_path_mkdir=$as_dir/$ac_prog$ac_exec_ext
-	       break 3;;
-	   esac
-	 done
-       done
-done
-IFS=$as_save_IFS
-
-fi
-
-  if test "${ac_cv_path_mkdir+set}" = set; then
-    MKDIR_P="$ac_cv_path_mkdir -p"
+  # On NextStep and OpenStep, the `mkdir' command does not
+  # recognize any option.  It will interpret all options as
+  # directories to create, and then abort because `.' already
+  # exists.
+  for d in ./-p ./--version;
+  do
+    test -d $d && rmdir $d
+  done
+  # $(mkinstalldirs) is defined by Automake if mkinstalldirs exists.
+  if test -f "$ac_aux_dir/mkinstalldirs"; then
+    mkdir_p='$(mkinstalldirs)'
   else
-    # As a last resort, use the slow shell script.  Don't cache a
-    # value for MKDIR_P within a source directory, because that will
-    # break other packages using the cache if that directory is
-    # removed, or if the value is a relative name.
-    test -d ./--version && rmdir ./--version
-    MKDIR_P="$ac_install_sh -d"
+    mkdir_p='$(install_sh) -d'
   fi
 fi
-{ echo "$as_me:$LINENO: result: $MKDIR_P" >&5
-echo "${ECHO_T}$MKDIR_P" >&6; }
-
-mkdir_p="$MKDIR_P"
-case $mkdir_p in
-  [\\/$]* | ?:[\\/]*) ;;
-  */*) mkdir_p="\$(top_builddir)/$mkdir_p" ;;
-esac
 
 
 
@@ -56587,7 +56618,9 @@ _ACEOF
 fi
 
 
- if test "x${USE_NLS}" = xyes; then
+
+
+if test "x${USE_NLS}" = xyes; then
   USE_NLS_TRUE=
   USE_NLS_FALSE='#'
 else
@@ -56595,7 +56628,9 @@ else
   USE_NLS_FALSE=
 fi
 
- if test "x${USE_INCLUDED_LIBINTL}" = xyes; then
+
+
+if test "x${USE_INCLUDED_LIBINTL}" = xyes; then
   BUILD_LIBINTL_TRUE=
   BUILD_LIBINTL_FALSE='#'
 else
@@ -57328,7 +57363,6 @@ gives unlimited permission to copy, distribute and modify it."
 ac_pwd='$ac_pwd'
 srcdir='$srcdir'
 INSTALL='$INSTALL'
-MKDIR_P='$MKDIR_P'
 _ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
@@ -58275,11 +58309,6 @@ ac_abs_srcdir=$ac_abs_top_srcdir$ac_dir_suffix
   [\\/$]* | ?:[\\/]* ) ac_INSTALL=$INSTALL ;;
   *) ac_INSTALL=$ac_top_build_prefix$INSTALL ;;
   esac
-  ac_MKDIR_P=$MKDIR_P
-  case $MKDIR_P in
-  [\\/$]* | ?:[\\/]* ) ;;
-  */*) ac_MKDIR_P=$ac_top_build_prefix$MKDIR_P ;;
-  esac
 _ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
@@ -58333,7 +58362,6 @@ s&@builddir@&$ac_builddir&;t t
 s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
-s&@MKDIR_P@&$ac_MKDIR_P&;t t
 $ac_datarootdir_hack
 " $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" | sed -f "$tmp/subs-4.sed" >$tmp/out
 
