barebones support for experimenting with the TRE library
git-svn-id: https://svn.r-project.org/R/trunk@49604 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -831,6 +831,9 @@ MAINTAINER_MODE_TRUE
 MAINTAINER_MODE_FALSE
 BUILD_HTML_TRUE
 BUILD_HTML_FALSE
+USE_TRE
+BUILD_TRE_TRUE
+BUILD_TRE_FALSE
 R_PRINTCMD
 R_PAPERSIZE
 R_BATCHSAVE
@@ -1790,6 +1793,7 @@ Optional Packages:
   --with-recommended-packages
                           use/install recommended R packages [yes]
   --with-ICU              use ICU library [yes]
+  --with-TRE              use TRE library [no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-x                use the X Window System
@@ -2992,6 +2996,37 @@ else
   use_ICU=yes
 fi
 
+
+## TRE
+
+# Check whether --with-TRE was given.
+if test "${with_TRE+set}" = set; then
+  withval=$with_TRE; if test "${withval}" = no; then
+  use_TRE=no
+else
+  use_TRE=yes
+fi
+
+else
+  use_TRE=no
+fi
+
+if test "$use_TRE" = yes ; then
+  LIBS="${LIBS} -ltre"
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_TRE 1
+_ACEOF
+
+fi
+
+ if test "x${use_TRE}" = "xyes"; then
+  BUILD_TRE_TRUE=
+  BUILD_TRE_FALSE='#'
+else
+  BUILD_TRE_TRUE='#'
+  BUILD_TRE_FALSE=
+fi
 
 
 ### ** Precious variables.
@@ -8236,13 +8271,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:8239: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:8274: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:8242: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:8277: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:8245: output\"" >&5)
+  (eval echo "\"\$as_me:8280: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -11685,11 +11720,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11688: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11723: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11692: \$? = $ac_status" >&5
+   echo "$as_me:11727: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12024,11 +12059,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12027: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12062: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12031: \$? = $ac_status" >&5
+   echo "$as_me:12066: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12129,11 +12164,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12132: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12167: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12136: \$? = $ac_status" >&5
+   echo "$as_me:12171: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12184,11 +12219,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12187: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12222: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12191: \$? = $ac_status" >&5
+   echo "$as_me:12226: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14940,7 +14975,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 14943 "configure"
+#line 14978 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15036,7 +15071,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 15039 "configure"
+#line 15074 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17041,11 +17076,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17044: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17079: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17048: \$? = $ac_status" >&5
+   echo "$as_me:17083: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17140,11 +17175,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17143: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17178: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17147: \$? = $ac_status" >&5
+   echo "$as_me:17182: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17192,11 +17227,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17195: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17230: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17199: \$? = $ac_status" >&5
+   echo "$as_me:17234: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18600,11 +18635,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18603: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18638: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18607: \$? = $ac_status" >&5
+   echo "$as_me:18642: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18699,11 +18734,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18702: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18737: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18706: \$? = $ac_status" >&5
+   echo "$as_me:18741: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18751,11 +18786,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18754: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18789: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18758: \$? = $ac_status" >&5
+   echo "$as_me:18793: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27461,7 +27496,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:27464: \"$ac_link\") >&5
+(eval echo $as_me:27499: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -27544,7 +27579,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:27547: \"$ac_link\") >&5
+(eval echo $as_me:27582: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -39690,7 +39725,6 @@ fi
 
 
 
-
 ## X11.
 { echo "$as_me:$LINENO: checking for X" >&5
 echo $ECHO_N "checking for X... $ECHO_C" >&6; }
@@ -47881,11 +47915,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:47884: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:47918: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:47888: \$? = $ac_status" >&5
+   echo "$as_me:47922: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -47980,11 +48014,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:47983: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48017: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:47987: \$? = $ac_status" >&5
+   echo "$as_me:48021: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -48032,11 +48066,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48035: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48069: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48039: \$? = $ac_status" >&5
+   echo "$as_me:48073: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -58279,6 +58313,13 @@ echo "$as_me: error: conditional \"BUILD_HTML\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_TRE_TRUE}" && test -z "${BUILD_TRE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TRE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TRE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${CROSS_COMPILING_TRUE}" && test -z "${CROSS_COMPILING_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CROSS_COMPILING\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -59631,6 +59672,9 @@ MAINTAINER_MODE_TRUE!$MAINTAINER_MODE_TRUE$ac_delim
 MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
 BUILD_HTML_TRUE!$BUILD_HTML_TRUE$ac_delim
 BUILD_HTML_FALSE!$BUILD_HTML_FALSE$ac_delim
+USE_TRE!$USE_TRE$ac_delim
+BUILD_TRE_TRUE!$BUILD_TRE_TRUE$ac_delim
+BUILD_TRE_FALSE!$BUILD_TRE_FALSE$ac_delim
 R_PRINTCMD!$R_PRINTCMD$ac_delim
 R_PAPERSIZE!$R_PAPERSIZE$ac_delim
 R_BATCHSAVE!$R_BATCHSAVE$ac_delim
@@ -59647,9 +59691,6 @@ SHLIB_LD!$SHLIB_LD$ac_delim
 SHLIB_LDFLAGS!$SHLIB_LDFLAGS$ac_delim
 DYLIB_LD!$DYLIB_LD$ac_delim
 DYLIB_LDFLAGS!$DYLIB_LDFLAGS$ac_delim
-CXXPICFLAGS!$CXXPICFLAGS$ac_delim
-SHLIB_CXXLD!$SHLIB_CXXLD$ac_delim
-SHLIB_CXXLDFLAGS!$SHLIB_CXXLDFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 85; then
@@ -59707,6 +59748,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CXXPICFLAGS!$CXXPICFLAGS$ac_delim
+SHLIB_CXXLD!$SHLIB_CXXLD$ac_delim
+SHLIB_CXXLDFLAGS!$SHLIB_CXXLDFLAGS$ac_delim
 SHLIB_FCD!$SHLIB_FCD$ac_delim
 SHLIB_FCLDFLAGS!$SHLIB_FCLDFLAGS$ac_delim
 TCLTK_LIBS!$TCLTK_LIBS$ac_delim
@@ -59801,9 +59845,6 @@ LIPO!$LIPO$ac_delim
 OTOOL!$OTOOL$ac_delim
 OTOOL64!$OTOOL64$ac_delim
 LIBTOOL_DEPS!$LIBTOOL_DEPS$ac_delim
-BUILD_CC!$BUILD_CC$ac_delim
-BUILD_R!$BUILD_R$ac_delim
-CROSS_COMPILING_TRUE!$CROSS_COMPILING_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -59845,6 +59886,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+BUILD_CC!$BUILD_CC$ac_delim
+BUILD_R!$BUILD_R$ac_delim
+CROSS_COMPILING_TRUE!$CROSS_COMPILING_TRUE$ac_delim
 CROSS_COMPILING_FALSE!$CROSS_COMPILING_FALSE$ac_delim
 shlibpath_var!$shlibpath_var$ac_delim
 striplib!$striplib$ac_delim
@@ -59939,9 +59983,6 @@ JAVA_CPPFLAGS0!$JAVA_CPPFLAGS0$ac_delim
 FC!$FC$ac_delim
 FCFLAGS!$FCFLAGS$ac_delim
 ac_ct_FC!$ac_ct_FC$ac_delim
-FCFLAGS_f90!$FCFLAGS_f90$ac_delim
-FCFLAGS_f95!$FCFLAGS_f95$ac_delim
-SHLIB_FCLD!$SHLIB_FCLD$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -59983,6 +60024,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+FCFLAGS_f90!$FCFLAGS_f90$ac_delim
+FCFLAGS_f95!$FCFLAGS_f95$ac_delim
+SHLIB_FCLD!$SHLIB_FCLD$ac_delim
 R_LD_LIBRARY_PATH!$R_LD_LIBRARY_PATH$ac_delim
 R_JAVA_LD_LIBRARY_PATH!$R_JAVA_LD_LIBRARY_PATH$ac_delim
 USE_RECOMMENDED_PACKAGES_TRUE!$USE_RECOMMENDED_PACKAGES_TRUE$ac_delim
@@ -60038,7 +60082,7 @@ OSF_SH_BUG!$OSF_SH_BUG$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 56; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -61771,6 +61815,15 @@ if test -z "${r_external_libs}"; then
   r_external_libs="ICU"
 else
   r_external_libs="${r_external_libs}${separator}ICU"
+fi
+fi
+if test "${use_TRE}" = yes; then
+  separator=", "
+test -z "${separator}" && separator=" "
+if test -z "${r_external_libs}"; then
+  r_external_libs="tre"
+else
+  r_external_libs="${r_external_libs}${separator}tre"
 fi
 fi
 r_capabilities=
