Updated.
git-svn-id: https://svn.r-project.org/R/trunk@20976 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1116,6 +1116,7 @@ Optional Packages:
   --with-blas             use BLAS library, or specify it [yes]
   --with-readline         use readline library (if available) [yes]
   --with-gnome            use GNOME, or specify its prefix [no]
+  --with-aqua             use Aqua (if available) [no]
   --with-tcltk            use Tcl/Tk, or specify its library dir [yes]
   --with-tcl-config=TCL_CONFIG
                           specify location of tclConfig.sh []
@@ -2103,6 +2104,14 @@ else
 fi
 else
   want_gnome=no
+fi;
+
+## Aqua.
+
+# Check whether --with-aqua or --without-aqua was given.
+if test "${with_aqua+set}" = set; then
+  withval="$with_aqua"
+  want_aqua=yes
 fi;
 
 ## Tcl/Tk.
@@ -5364,7 +5373,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5367 "configure"' > conftest.$ac_ext
+  echo '#line 5376 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5900,7 +5909,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5903: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5912: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -7693,7 +7702,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7696 "configure"
+#line 7705 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7791,7 +7800,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7794 "configure"
+#line 7803 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9750,7 +9759,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:9753:" \
+echo "$as_me:9762:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -11838,49 +11847,41 @@ else
 #line $LINENO "configure"
 #include "confdefs.h"
 #include <setjmp.h>
-
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+sigjmp_buf b;
+sigsetjmp(b, 0);
+siglongjmp(b, 1);
+  ;
+  return 0;
+}
 _ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  egrep "sigjmp_buf" >/dev/null 2>&1; then
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
   r_cv_header_setjmp_posix=yes
 else
-  r_cv_header_setjmp_posix=no
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+r_cv_header_setjmp_posix=no
 fi
-rm -f conftest*
-
-if test "${r_cv_header_setjmp_posix}" = yes; then
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <setjmp.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  egrep "siglongjmp" >/dev/null 2>&1; then
-  :
-else
-  r_cv_header_setjmp_posix=no
-fi
-rm -f conftest*
-
-fi
-if test "${r_cv_header_setjmp_posix}" = yes; then
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <setjmp.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  egrep "sigsetjmp" >/dev/null 2>&1; then
-  :
-else
-  r_cv_header_setjmp_posix=no
-fi
-rm -f conftest*
-
-fi
-
+rm -f conftest.$ac_objext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $r_cv_header_setjmp_posix" >&5
 echo "${ECHO_T}$r_cv_header_setjmp_posix" >&6
@@ -12172,7 +12173,7 @@ if test "${r_cv_type_socklen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   for t in socklen_t size_t int; do
-    cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 #include <stddef.h>
@@ -12217,7 +12218,7 @@ cat conftest.$ac_ext >&5
 r_cv_type_socklen=
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
-  done
+done
 fi
 
 if test "x${r_cv_type_socklen}" = x; then
@@ -14138,7 +14139,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:14141: \"$ac_link\") >&5
+(eval echo $as_me:14142: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -14217,7 +14218,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:14220: \"$ac_link\") >&5
+(eval echo $as_me:14221: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -16732,7 +16733,9 @@ case "${host_os}" in
   darwin*)
     cpicflags="-fno-common"
     cxxpicflags="-fno-common"
-    fpicflags="-fno-common"
+    if test "${G77}" = yes; then
+      fpicflags="-fno-common"
+    fi
     ## <FIXME>
     ## Needed because currently the Quartz device driver gets linked to
     ## the main binary.  Change once the driver is modularized.
@@ -21013,6 +21016,20 @@ fi
 
 
 
+## Aqua
+use_aqua=no
+if test "${want_aqua}" = yes; then
+  case "${host_os}" in
+    darwin*)
+      use_aqua=yes
+      ;;
+  esac
+fi
+
+if test "${use_aqua}" = yes; then
+  R_GUIS="${R_GUIS} aqua";
+fi
+
 ## Tcl/Tk.
 if test "${want_tcltk}" = yes; then
   have_tcltk=yes
@@ -23523,7 +23540,7 @@ esac
 
 ac_config_headers="$ac_config_headers src/include/config.h"
 
-ac_config_files="$ac_config_files Makeconf Makefile afm/Makefile doc/Makefile doc/html/Makefile doc/html/search/Makefile doc/manual/Makefile etc/Makefile etc/Makeconf etc/Renviron m4/Makefile share/Makefile src/Makefile src/appl/Makefile src/extra/Makefile src/extra/xdr/Makefile src/extra/zlib/Makefile src/include/Makefile src/include/Rmath.h src/include/R_ext/Makefile src/library/Makefile src/library/base/DESCRIPTION src/library/base/Makefile src/library/ctest/DESCRIPTION src/library/ctest/Makefile src/library/ctest/src/Makefile src/library/eda/DESCRIPTION src/library/eda/Makefile src/library/eda/src/Makefile src/library/lqs/DESCRIPTION src/library/lqs/Makefile src/library/lqs/src/Makefile src/library/methods/DESCRIPTION src/library/methods/Makefile src/library/methods/src/Makefile src/library/modreg/DESCRIPTION src/library/modreg/Makefile src/library/modreg/src/Makefile src/library/mva/DESCRIPTION src/library/mva/Makefile src/library/mva/src/Makefile src/library/nls/DESCRIPTION src/library/nls/Makefile src/library/nls/src/Makefile src/library/profile/Makefile src/library/stepfun/DESCRIPTION src/library/stepfun/Makefile src/library/splines/DESCRIPTION src/library/splines/Makefile src/library/splines/src/Makefile src/library/tcltk/DESCRIPTION src/library/tcltk/Makefile src/library/tcltk/src/Makefile src/library/tools/DESCRIPTION src/library/tools/Makefile src/library/ts/DESCRIPTION src/library/ts/Makefile src/library/ts/src/Makefile src/main/Makefile src/modules/Makefile src/modules/X11/Makefile src/modules/gnome/Makefile src/modules/internet/Makefile src/modules/lapack/Makefile src/modules/vfonts/Makefile src/nmath/Makefile src/nmath/standalone/Makefile src/scripts/Makefile src/scripts/COMPILE src/scripts/INSTALL src/scripts/REMOVE src/scripts/R.sh src/scripts/Rdconv src/scripts/Rdindex src/scripts/Rprof src/scripts/SHLIB src/scripts/Sd2Rd src/scripts/build src/scripts/check src/scripts/f77 src/unix/Makefile tests/Makefile tests/Embedding/Makefile tests/Examples/Makefile tests/Native/Makefile tools/Makefile"
+ac_config_files="$ac_config_files Makeconf Makefile afm/Makefile doc/Makefile doc/html/Makefile doc/html/search/Makefile doc/manual/Makefile etc/Makefile etc/Makeconf etc/Renviron m4/Makefile share/Makefile src/Makefile src/appl/Makefile src/extra/Makefile src/extra/xdr/Makefile src/extra/zlib/Makefile src/include/Makefile src/include/Rmath.h src/include/R_ext/Makefile src/library/Makefile src/library/base/DESCRIPTION src/library/base/Makefile src/library/ctest/DESCRIPTION src/library/ctest/Makefile src/library/ctest/src/Makefile src/library/eda/DESCRIPTION src/library/eda/Makefile src/library/eda/src/Makefile src/library/lqs/DESCRIPTION src/library/lqs/Makefile src/library/lqs/src/Makefile src/library/methods/DESCRIPTION src/library/methods/Makefile src/library/methods/src/Makefile src/library/modreg/DESCRIPTION src/library/modreg/Makefile src/library/modreg/src/Makefile src/library/mva/DESCRIPTION src/library/mva/Makefile src/library/mva/src/Makefile src/library/nls/DESCRIPTION src/library/nls/Makefile src/library/nls/src/Makefile src/library/profile/Makefile src/library/stepfun/DESCRIPTION src/library/stepfun/Makefile src/library/splines/DESCRIPTION src/library/splines/Makefile src/library/splines/src/Makefile src/library/tcltk/DESCRIPTION src/library/tcltk/Makefile src/library/tcltk/src/Makefile src/library/tools/DESCRIPTION src/library/tools/Makefile src/library/ts/DESCRIPTION src/library/ts/Makefile src/library/ts/src/Makefile src/main/Makefile src/modules/Makefile src/modules/X11/Makefile src/modules/aqua/Makefile src/modules/gnome/Makefile src/modules/internet/Makefile src/modules/lapack/Makefile src/modules/vfonts/Makefile src/nmath/Makefile src/nmath/standalone/Makefile src/scripts/Makefile src/scripts/COMPILE src/scripts/INSTALL src/scripts/REMOVE src/scripts/R.sh src/scripts/Rdconv src/scripts/Rdindex src/scripts/Rprof src/scripts/SHLIB src/scripts/Sd2Rd src/scripts/build src/scripts/check src/scripts/f77 src/unix/Makefile tests/Makefile tests/Embedding/Makefile tests/Examples/Makefile tests/Native/Makefile tools/Makefile"
 
 
 
@@ -24075,6 +24092,7 @@ do
   "src/main/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/main/Makefile" ;;
   "src/modules/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/Makefile" ;;
   "src/modules/X11/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/X11/Makefile" ;;
+  "src/modules/aqua/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/aqua/Makefile" ;;
   "src/modules/gnome/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/gnome/Makefile" ;;
   "src/modules/internet/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/internet/Makefile" ;;
   "src/modules/lapack/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/modules/lapack/Makefile" ;;
