require 'stat' and 'opendir' calls (as we used to without testing)
git-svn-id: https://svn.r-project.org/R/trunk@41349 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35040,6 +35040,17 @@ fi
 done
 
 
+## we can't use dir() or unlink(recursive=TRUE) without these
+if test "${ac_cv_have_decl_stat}" = "no"; then
+   { { echo "$as_me:$LINENO: error: Building R requires the 'stat' system call" >&5
+echo "$as_me: error: Building R requires the 'stat' system call" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "${ac_cv_search_opendir}" = "no"; then
+   { { echo "$as_me:$LINENO: error: Building R requires the 'opendir' system call" >&5
+echo "$as_me: error: Building R requires the 'opendir' system call" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 ## <NOTE>
