Updated.
git-svn-id: https://svn.r-project.org/R/trunk@19348 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15500,7 +15500,7 @@ fi
 rm -f conftest*
 
 
-    ac_safe=`echo "-mieee-fp" | sed 'y%./+-:%__p__%'`
+    ac_safe=`echo "-mieee-fp" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -mieee-fp" >&5
 echo $ECHO_N "checking whether ${CC-cc} accepts -mieee-fp... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cc_flag_${ac_safe}+set}\" = set"; then
@@ -15571,7 +15571,7 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-ac_safe=`echo "-mieee-fp" | sed 'y%./+-:%__p__%'`
+ac_safe=`echo "-mieee-fp" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CXX-c++} accepts -mieee-fp" >&5
 echo $ECHO_N "checking whether ${CXX-c++} accepts -mieee-fp... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cxx_flag_${ac_safe}+set}\" = set"; then
@@ -15644,13 +15644,21 @@ fi
     ;;
   alpha*)
     ## <NOTE>
-    ## We really need to use '-ieee_with_inexact' ('-mieee-with-inexact'
-    ## for GCC) for the C compiler: '-ieee'/'-mieee' are not enough.
-    ## What about the FORTRAN 77 and C++ compilers?
-    ## According to <Albrecht.Gebhardt@uni-klu.ac.at>, native FORTRAN
-    ## on Alpha/OSF maps '-ieee' to '-fpe3' which was used previously.
+    ## * ANSI C
+    ## The native C compiler needs @option{-std1}: AC_PROG_CC_STDC
+    ## passes all ANSI C tests with no extra flags but then __STDC__ is
+    ## undefined which breaks compilation of the connections code.
+    ## * IEEE math
+    ## We really need to use @option{-ieee_with_inexact} (called
+    ## @option{-mieee-with-inexact} for GCC) for the C compiler:
+    ## @option{-ieee} (or @option{-mieee}) are not enough.
+    ## According to <Albrecht.Gebhardt@uni-klu.ac.at> and Luke Tierney
+    ## <luke@stat.umn.edu>, @option{-fpe3} is what we want for the
+    ## native FORTRAN 77 compiler: seems that not all versions map
+    ## @option{-ieee} to @option{-fpe3}.
+    ## What about the C++ compilers?
     if test "${GCC}" = yes; then
-      ac_safe=`echo "-mieee-with-inexact" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-mieee-with-inexact" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -mieee-with-inexact" >&5
 echo $ECHO_N "checking whether ${CC-cc} accepts -mieee-with-inexact... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cc_flag_${ac_safe}+set}\" = set"; then
@@ -15721,7 +15729,77 @@ echo "${ECHO_T}no" >&6
 fi
 
     else
-      ac_safe=`echo "-ieee_with_inexact" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-std1" | sed 'y%./+-:=%__p___%'`
+echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -std1" >&5
+echo $ECHO_N "checking whether ${CC-cc} accepts -std1... $ECHO_C" >&6
+if eval "test \"\${r_cv_prog_cc_flag_${ac_safe}+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+r_save_CFLAGS="${CFLAGS}"
+CFLAGS="${CFLAGS} -std1"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "r_cv_prog_cc_flag_${ac_safe}=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "r_cv_prog_cc_flag_${ac_safe}=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+CFLAGS="${r_save_CFLAGS}"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+
+if eval "test \"`echo '$r_cv_prog_cc_flag_'$ac_safe`\" = yes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  R_XTRA_CFLAGS="${R_XTRA_CFLAGS} -std1"
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+      ac_safe=`echo "-ieee_with_inexact" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -ieee_with_inexact" >&5
 echo $ECHO_N "checking whether ${CC-cc} accepts -ieee_with_inexact... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cc_flag_${ac_safe}+set}\" = set"; then
@@ -15793,7 +15871,7 @@ fi
 
     fi
     if test "${G77}" = yes; then
-      ac_safe=`echo "-mieee" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-mieee" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${F77-f77} accepts -mieee" >&5
 echo $ECHO_N "checking whether ${F77-f77} accepts -mieee... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_f77_flag_${ac_safe}+set}\" = set"; then
@@ -15850,9 +15928,9 @@ echo "${ECHO_T}no" >&6
 fi
 
     else
-      ac_safe=`echo "-ieee" | sed 'y%./+-:%__p__%'`
-echo "$as_me:$LINENO: checking whether ${F77-f77} accepts -ieee" >&5
-echo $ECHO_N "checking whether ${F77-f77} accepts -ieee... $ECHO_C" >&6
+      ac_safe=`echo "-fpe3" | sed 'y%./+-:=%__p___%'`
+echo "$as_me:$LINENO: checking whether ${F77-f77} accepts -fpe3" >&5
+echo $ECHO_N "checking whether ${F77-f77} accepts -fpe3... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_f77_flag_${ac_safe}+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -15862,7 +15940,7 @@ ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 
 r_save_FFLAGS="${FFLAGS}"
-FFLAGS="${FFLAGS} -ieee"
+FFLAGS="${FFLAGS} -fpe3"
 cat >conftest.$ac_ext <<_ACEOF
       program main
 
@@ -15900,7 +15978,7 @@ fi
 if eval "test \"`echo '$r_cv_prog_f77_flag_'$ac_safe`\" = yes"; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-  R_XTRA_FFLAGS="${R_XTRA_FFLAGS} -ieee"
+  R_XTRA_FFLAGS="${R_XTRA_FFLAGS} -fpe3"
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -15908,7 +15986,7 @@ fi
 
     fi
     if test "${GXX}" = yes; then
-      ac_safe=`echo "-mieee" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-mieee" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CXX-c++} accepts -mieee" >&5
 echo $ECHO_N "checking whether ${CXX-c++} accepts -mieee... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cxx_flag_${ac_safe}+set}\" = set"; then
@@ -15979,7 +16057,7 @@ echo "${ECHO_T}no" >&6
 fi
 
     else
-      ac_safe=`echo "-ieee" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-ieee" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CXX-c++} accepts -ieee" >&5
 echo $ECHO_N "checking whether ${CXX-c++} accepts -ieee... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cxx_flag_${ac_safe}+set}\" = set"; then
@@ -16064,7 +16142,7 @@ case "${host_os}" in
 _ACEOF
 
     if test "${GCC}" = yes; then
-      ac_safe=`echo "-mno-fp-in-toc" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-mno-fp-in-toc" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CC-cc} accepts -mno-fp-in-toc" >&5
 echo $ECHO_N "checking whether ${CC-cc} accepts -mno-fp-in-toc... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cc_flag_${ac_safe}+set}\" = set"; then
@@ -16279,7 +16357,7 @@ fi
     ## compilers *need* '-OPT:IEEE_NaN_inf=ON'.  Currently, all we do is
     ## check whether the non-GNU tools *accept* the flag.
     if test "${G77}" != yes; then
-      ac_safe=`echo "-OPT:IEEE_NaN_inf=ON" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-OPT:IEEE_NaN_inf=ON" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${F77-f77} accepts -OPT:IEEE_NaN_inf=ON" >&5
 echo $ECHO_N "checking whether ${F77-f77} accepts -OPT:IEEE_NaN_inf=ON... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_f77_flag_${ac_safe}+set}\" = set"; then
@@ -16337,7 +16415,7 @@ fi
 
     fi
     if test "${GXX}" != yes; then
-      ac_safe=`echo "-OPT:IEEE_NaN_inf=ON" | sed 'y%./+-:%__p__%'`
+      ac_safe=`echo "-OPT:IEEE_NaN_inf=ON" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CXX-c++} accepts -OPT:IEEE_NaN_inf=ON" >&5
 echo $ECHO_N "checking whether ${CXX-c++} accepts -OPT:IEEE_NaN_inf=ON... $ECHO_C" >&6
 if eval "test \"\${r_cv_prog_cxx_flag_${ac_safe}+set}\" = set"; then
