increase requirements for external zlib, bzlib and pcre to ensure that the versions are at least as secure as those shipping with R.
git-svn-id: https://svn.r-project.org/R/trunk@44853 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -43566,8 +43566,8 @@ fi
 
   fi
   if test "${have_zlib}" = yes; then
-    { echo "$as_me:$LINENO: checking if zlib version >= 1.2.1" >&5
-echo $ECHO_N "checking if zlib version >= 1.2.1... $ECHO_C" >&6; }
+    { echo "$as_me:$LINENO: checking if zlib version >= 1.2.3" >&5
+echo $ECHO_N "checking if zlib version >= 1.2.3... $ECHO_C" >&6; }
 if test "${r_cv_header_zlib_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -43586,7 +43586,7 @@ cat >>conftest.$ac_ext <<_ACEOF
 #include <zlib.h>
 int main() {
 #ifdef ZLIB_VERSION
-  exit(strcmp(ZLIB_VERSION, "1.2.1") < 0);
+  exit(strcmp(ZLIB_VERSION, "1.2.3") < 0);
 #else
   exit(1);
 #endif
@@ -43943,6 +43943,71 @@ fi
 else
   have_bzlib=no
 fi
+if test "x${have_bzlib}" = xyes; then
+{ echo "$as_me:$LINENO: checking if bzip2 version >= 1.0.5" >&5
+echo $ECHO_N "checking if bzip2 version >= 1.0.5... $ECHO_C" >&6; }
+if test "${r_cv_have_bzlib+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  r_cv_have_bzlib=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_BZLIB_H
+#include <bzlib.h>
+#endif
+int main() {
+    char *ver = BZ2_bzlibVersion();
+    exit(strcmp(ver, "1.0.5") < 0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  r_cv_have_bzlib=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+r_cv_have_bzlib=no
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+fi
+{ echo "$as_me:$LINENO: result: $r_cv_have_bzlib" >&5
+echo "${ECHO_T}$r_cv_have_bzlib" >&6; }
+fi
+if test "x${r_cv_have_bzlib}" = xno; then
+  have_bzlib=no
+fi
 { echo "$as_me:$LINENO: checking whether bzip2 support needs to be compiled" >&5
 echo $ECHO_N "checking whether bzip2 support needs to be compiled... $ECHO_C" >&6; }
 if test "x${have_bzlib}" = xyes; then
@@ -44196,13 +44261,13 @@ else
   have_pcre=no
 fi
 if test "x${have_pcre}" = xyes; then
-{ echo "$as_me:$LINENO: checking if PCRE version >= 4.0" >&5
-echo $ECHO_N "checking if PCRE version >= 4.0... $ECHO_C" >&6; }
-if test "${r_cv_have_pcre4+set}" = set; then
+{ echo "$as_me:$LINENO: checking if PCRE version >= 7.6" >&5
+echo $ECHO_N "checking if PCRE version >= 7.6... $ECHO_C" >&6; }
+if test "${r_cv_have_pcre76+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   if test "$cross_compiling" = yes; then
-  r_cv_have_pcre4=no
+  r_cv_have_pcre76=no
 else
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -44220,7 +44285,13 @@ cat >>conftest.$ac_ext <<_ACEOF
 #endif
 int main() {
 #ifdef PCRE_MAJOR
-  exit(PCRE_MAJOR<4);
+#if PCRE_MAJOR > 7
+  exit(0);
+#elif PCRE_MAJOR > 6 && PCRE_MAJOR >= 6
+  exit(0);
+#else
+  exit(1);
+#endif
 #else
   exit(1);
 #endif
@@ -44247,36 +44318,36 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  r_cv_have_pcre4=yes
+  r_cv_have_pcre76=yes
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-r_cv_have_pcre4=no
+r_cv_have_pcre76=no
 fi
 rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 
 
 fi
-{ echo "$as_me:$LINENO: result: $r_cv_have_pcre4" >&5
-echo "${ECHO_T}$r_cv_have_pcre4" >&6; }
+{ echo "$as_me:$LINENO: result: $r_cv_have_pcre76" >&5
+echo "${ECHO_T}$r_cv_have_pcre76" >&6; }
 fi
-if test "x${r_cv_have_pcre4}" = xyes; then
+if test "x${r_cv_have_pcre76}" = xyes; then
   LIBS="-lpcre ${LIBS}"
 fi
 { echo "$as_me:$LINENO: checking whether PCRE support needs to be compiled" >&5
 echo $ECHO_N "checking whether PCRE support needs to be compiled... $ECHO_C" >&6; }
-if test "x${r_cv_have_pcre4}" = xyes; then
+if test "x${r_cv_have_pcre76}" = xyes; then
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 else
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 fi
- if test "x${r_cv_have_pcre4}" != xyes; then
+ if test "x${r_cv_have_pcre76}" != xyes; then
   BUILD_PCRE_TRUE=
   BUILD_PCRE_FALSE='#'
 else
@@ -47189,11 +47260,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:47192: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:47263: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:47196: \$? = $ac_status" >&5
+   echo "$as_me:47267: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -47288,11 +47359,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:47291: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:47362: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:47295: \$? = $ac_status" >&5
+   echo "$as_me:47366: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -47340,11 +47411,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:47343: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:47414: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:47347: \$? = $ac_status" >&5
+   echo "$as_me:47418: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
