find if SIZE_MAX is declared, and if it is use it for R_SIZE_T_MAX
git-svn-id: https://svn.r-project.org/R/trunk@30767 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22362,8 +22362,9 @@ fi
 
 
 
+
 for ac_header in arpa/inet.h dl.h dlfcn.h elf.h fcntl.h floatingpoint.h \
-  fpu_control.h grp.h ieee754.h ieeefp.h locale.h \
+  fpu_control.h grp.h ieee754.h ieeefp.h limits.h locale.h \
   netdb.h netinet/in.h \
   pwd.h readline/history.h readline/readline.h strings.h \
   sys/param.h sys/select.h sys/socket.h sys/stat.h sys/time.h \
@@ -22678,6 +22679,7 @@ done
 ## But then we want full gettext support and AM_GNU_GETTEXT.
 ## AC_CHECK_HEADERS(libintl.h)
 ## </NOTE>
+
 case "${host_os}" in
   sunos4*)
 
@@ -22987,6 +22989,76 @@ else
 
 cat >>confdefs.h <<_ACEOF
 #define size_t unsigned
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking whether SIZE_MAX is declared" >&5
+echo $ECHO_N "checking whether SIZE_MAX is declared... $ECHO_C" >&6
+if test "${r_cv_size_max+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  r_cv_size_max=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <stdlib.h>
+#ifdef HAVE_INTTYPES_H
+#  include <inttypes.h>
+#endif
+#ifdef HAVE_STDINT_H
+#  include <stdint.h>
+#endif
+#ifdef HAVE_LIMITS_H
+#  include <limits.h>
+#endif
+
+int
+main() {
+#ifndef SIZE_MAX
+  char *p = (char *) SIZE_MAX;
+#endif
+
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  r_cv_size_max=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+r_cv_size_max=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $r_cv_size_max" >&5
+echo "${ECHO_T}$r_cv_size_max" >&6
+if test "x${r_cv_size_max}" = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DECL_SIZE_MAX 1
 _ACEOF
 
 fi
@@ -25378,7 +25450,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:25381: \"$ac_link\") >&5
+(eval echo $as_me:25453: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -25456,7 +25528,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:25459: \"$ac_link\") >&5
+(eval echo $as_me:25531: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
