add different test for BUILD_DLFCN_DARWIN for Tiger aka darwin8
git-svn-id: https://svn.r-project.org/R/trunk@32272 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21489,7 +21489,7 @@ fi
 fi
 
 case "${host_os}" in
-  darwin*)
+  darwin1234567.*)
 
 
 if true; then
@@ -21502,6 +21502,87 @@ fi
     ## SI says we want '-lcc_dynamic' on Darwin, although currently
     ## http://developer.apple.com /documentation/MacOSX/ has nothing
     ## official.
+
+echo "$as_me:$LINENO: checking for main in -lcc_dynamic" >&5
+echo $ECHO_N "checking for main in -lcc_dynamic... $ECHO_C" >&6
+if test "${ac_cv_lib_cc_dynamic_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcc_dynamic  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_cc_dynamic_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_cc_dynamic_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_cc_dynamic_main" >&5
+echo "${ECHO_T}$ac_cv_lib_cc_dynamic_main" >&6
+if test $ac_cv_lib_cc_dynamic_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCC_DYNAMIC 1
+_ACEOF
+
+  LIBS="-lcc_dynamic $LIBS"
+
+fi
+
+    ;;
+  darwin*)
+    ## 'Tiger' = 10.4 is darwin8 and includes dl*
+    ## We assume darwin9.*, 10.* etc will too.
+
+
+if false; then
+  BUILD_DLFCN_DARWIN_TRUE=
+  BUILD_DLFCN_DARWIN_FALSE='#'
+else
+  BUILD_DLFCN_DARWIN_TRUE='#'
+  BUILD_DLFCN_DARWIN_FALSE=
+fi
 
 echo "$as_me:$LINENO: checking for main in -lcc_dynamic" >&5
 echo $ECHO_N "checking for main in -lcc_dynamic... $ECHO_C" >&6
@@ -25488,7 +25569,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:25491: \"$ac_link\") >&5
+(eval echo $as_me:25572: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -25566,7 +25647,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:25569: \"$ac_link\") >&5
+(eval echo $as_me:25650: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -25812,7 +25893,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:25815: \"$ac_link\") >&5
+(eval echo $as_me:25896: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -25894,7 +25975,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:25897: \"$ac_link\") >&5
+(eval echo $as_me:25978: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
