add test for wctrans_t which is apparently missing on IRIX
git-svn-id: https://svn.r-project.org/R/trunk@35162 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34090,14 +34090,87 @@ _ACEOF
 fi
 
 
-for ac_func in mbrtowc mbstowcs wcrtomb wcscoll wcsftime wcstombs \
-               wctrans
+for ac_func in mbrtowc mbstowcs wcrtomb wcscoll wcsftime wcstombs wctrans
 do
 this=`echo "ac_cv_func_$ac_func"`
 if test "x$this" = xno; then
   want_mbcs_support=no
 fi
 done
+fi
+if test "$want_mbcs_support" = yes ; then
+  echo "$as_me:$LINENO: checking for wctrans_t" >&5
+echo $ECHO_N "checking for wctrans_t... $ECHO_C" >&6
+if test "${r_cv_c_wctrans_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <wchar.h>
+       #include <wctype.h>
+       wctrans_t tr;
+#ifdef F77_DUMMY_MAIN
+
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  r_cv_c_wctrans_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+r_cv_c_wctrans_t=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $r_cv_c_wctrans_t" >&5
+echo "${ECHO_T}$r_cv_c_wctrans_t" >&6
+  if test $r_cv_c_wctrans_t = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_WCTRANS_T 1
+_ACEOF
+
+  else
+    want_mbcs_support=no
+  fi
 fi
 if test "x${want_mbcs_support}" = xyes; then
 
