fix some cache problems with Aqua configuration conditionalize Darwin stuff update description of what HAVE_AQUA does
git-svn-id: https://svn.r-project.org/R/trunk@47534 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29140,6 +29140,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
   fi # -n ${OBJC}
 
 
+case "${host_os}" in
+  darwin*)
 
   ac_objc_foundation=no
   if test -n "${OBJC}"; then
@@ -29562,6 +29564,8 @@ fi
 { echo "$as_me:$LINENO: result: $r_cv_objc_foundation" >&5
 echo "${ECHO_T}$r_cv_objc_foundation" >&6; }
 
+  ;;
+esac
 
 ### ** Platform-specific overrides for the C, Fortran 77 and C++ compilers.
 
@@ -38010,9 +38014,10 @@ fi
     { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    if test "${have_vecLib_fw}" = "yes"; then
+    ## NB: this lot is not cached
+    if test -n "${r_cv_check_fw_vecLib}"; then
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
       ## for vecLib we have a work-around by using cblas_..._sub
       use_veclib_g95fix=yes
       ## The fix may not work with internal lapack, because
@@ -38021,6 +38026,8 @@ echo "${ECHO_T}no" >&6; }
       #      use_lapack=yes
       #	     with_lapack=""
     else
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
       BLAS_LIBS=
       acx_blas_ok="no"
     fi
@@ -42117,9 +42124,13 @@ fi
 
 fi
 
-## check for CoreFoundation framework (chances are much higher
-## that we can build AQUA if this one is present)
- { echo "$as_me:$LINENO: checking for CFStringGetSystemEncoding in CoreFoundation framework" >&5
+
+## Aqua
+case "${host_os}" in
+  darwin*)
+    ## check for CoreFoundation framework (chances are much higher
+    ## that we can build AQUA if this one is present)
+     { echo "$as_me:$LINENO: checking for CFStringGetSystemEncoding in CoreFoundation framework" >&5
 echo $ECHO_N "checking for CFStringGetSystemEncoding in CoreFoundation framework... $ECHO_C" >&6; }
 if test "${r_cv_check_fw_CoreFoundation+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -42202,16 +42213,17 @@ fi
 { echo "$as_me:$LINENO: result: $r_cv_check_fw_CoreFoundation" >&5
 echo "${ECHO_T}$r_cv_check_fw_CoreFoundation" >&6; }
 
-
-## Aqua
-use_aqua=no
+    use_aqua=no
 if test "${want_aqua}" = yes; then
   case "${host_os}" in
     darwin*)
       ## we can build AQUA only with CoreFoundation, otherwise
       ## Quartz device won't build
-      if test "${have_CoreFoundation_fw}" = yes; then
+      if test -n "${r_cv_check_fw_CoreFoundation}" ; then
         use_aqua=yes
+      else
+        { echo "$as_me:$LINENO: WARNING: requested 'aqua' but CoreFoundation was not found" >&5
+echo "$as_me: WARNING: requested 'aqua' but CoreFoundation was not found" >&2;}
       fi
       ;;
   esac
@@ -42224,6 +42236,11 @@ _ACEOF
 
 fi
 
+  ;;
+  *)
+    use_aqua=no
+  ;;
+esac
  if test "x${use_aqua}" = xyes; then
   BUILD_AQUA_TRUE=
   BUILD_AQUA_FALSE='#'
@@ -48045,11 +48062,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48048: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48065: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:48052: \$? = $ac_status" >&5
+   echo "$as_me:48069: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -48144,11 +48161,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48147: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48164: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48151: \$? = $ac_status" >&5
+   echo "$as_me:48168: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -48196,11 +48213,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48199: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48216: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48203: \$? = $ac_status" >&5
+   echo "$as_me:48220: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
