support ICU 4.0
git-svn-id: https://svn.r-project.org/R/trunk@47309 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39694,6 +39694,85 @@ fi
 if test "$use_ICU" = yes ; then
   ## FIXME: later, warn not error
 
+{ echo "$as_me:$LINENO: checking for ucol_open_4_0 in -licui18n" >&5
+echo $ECHO_N "checking for ucol_open_4_0 in -licui18n... $ECHO_C" >&6; }
+if test "${ac_cv_lib_icui18n_ucol_open_4_0+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-licui18n  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ucol_open_4_0 ();
+#ifdef F77_DUMMY_MAIN
+
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+
+#endif
+int
+main ()
+{
+return ucol_open_4_0 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_icui18n_ucol_open_4_0=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_icui18n_ucol_open_4_0=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_icui18n_ucol_open_4_0" >&5
+echo "${ECHO_T}$ac_cv_lib_icui18n_ucol_open_4_0" >&6; }
+if test $ac_cv_lib_icui18n_ucol_open_4_0 = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBICUI18N 1
+_ACEOF
+
+  LIBS="-licui18n $LIBS"
+
+else
+
+
 { echo "$as_me:$LINENO: checking for ucol_open_3_8 in -licui18n" >&5
 echo $ECHO_N "checking for ucol_open_3_8 in -licui18n... $ECHO_C" >&6; }
 if test "${ac_cv_lib_icui18n_ucol_open_3_8+set}" = set; then
@@ -39941,6 +40020,88 @@ fi
 fi
 
 
+fi
+
+
+{ echo "$as_me:$LINENO: checking for ucnv_fromUChars_4_0 in -licuuc" >&5
+echo $ECHO_N "checking for ucnv_fromUChars_4_0 in -licuuc... $ECHO_C" >&6; }
+if test "${ac_cv_lib_icuuc_ucnv_fromUChars_4_0+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-licuuc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ucnv_fromUChars_4_0 ();
+#ifdef F77_DUMMY_MAIN
+
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+
+#endif
+int
+main ()
+{
+return ucnv_fromUChars_4_0 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_icuuc_ucnv_fromUChars_4_0=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_icuuc_ucnv_fromUChars_4_0=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_icuuc_ucnv_fromUChars_4_0" >&5
+echo "${ECHO_T}$ac_cv_lib_icuuc_ucnv_fromUChars_4_0" >&6; }
+if test $ac_cv_lib_icuuc_ucnv_fromUChars_4_0 = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBICUUC 1
+_ACEOF
+
+  LIBS="-licuuc $LIBS"
+
+else
+
+
 { echo "$as_me:$LINENO: checking for ucnv_fromUChars_3_8 in -licuuc" >&5
 echo $ECHO_N "checking for ucnv_fromUChars_3_8 in -licuuc... $ECHO_C" >&6; }
 if test "${ac_cv_lib_icuuc_ucnv_fromUChars_3_8+set}" = set; then
@@ -40179,6 +40340,9 @@ else
   { { echo "$as_me:$LINENO: error: library 'icuuc' is required for ICU" >&5
 echo "$as_me: error: library 'icuuc' is required for ICU" >&2;}
    { (exit 1); exit 1; }; }
+fi
+
+
 fi
 
 
@@ -48513,11 +48677,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48516: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48680: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:48520: \$? = $ac_status" >&5
+   echo "$as_me:48684: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -48612,11 +48776,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48615: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48779: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48619: \$? = $ac_status" >&5
+   echo "$as_me:48783: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -48664,11 +48828,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48667: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48831: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48671: \$? = $ac_status" >&5
+   echo "$as_me:48835: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
