make configuring without recommended packages and without indicating an error
git-svn-id: https://svn.r-project.org/R/trunk@31541 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -37870,6 +37870,13 @@ fi
 echo "$as_me:$LINENO: result: $r_cv_misc_recommended_packages" >&5
 echo "${ECHO_T}$r_cv_misc_recommended_packages" >&6
 use_recommended_packages=${r_cv_misc_recommended_packages}
+if test "x${r_cv_misc_recommended_packages}" = xno; then
+  { { echo "$as_me:$LINENO: error: Some of the recommended packages are missing
+  Use --without-recommended-packages if this was intentional" >&5
+echo "$as_me: error: Some of the recommended packages are missing
+  Use --without-recommended-packages if this was intentional" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 fi
 
