first pass at supplying zlib if it is missing, and using it for gzfile only
git-svn-id: https://svn.r-project.org/R/trunk@17792 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14006,7 +14006,6 @@ EOF
 fi
 
 
-
 if test "${r_cv_xdr}" = no; then
   BUILD_XDR_TRUE=
   BUILD_XDR_FALSE='#'
@@ -14015,11 +14014,14 @@ else
   BUILD_XDR_FALSE=
 fi
 
+
 ## zlib headers and libraries.
 
+  echo "checking if zlib is installed or needs to be compiled" 1>&6
+echo "configure:14022: checking if zlib is installed or needs to be compiled" >&5
   have_zlib=no
   echo $ac_n "checking for gzopen in -lz""... $ac_c" 1>&6
-echo "configure:14023: checking for gzopen in -lz" >&5
+echo "configure:14025: checking for gzopen in -lz" >&5
 ac_lib_var=`echo z'_'gzopen | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -14027,7 +14029,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lz  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 14031 "configure"
+#line 14033 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -14038,7 +14040,7 @@ int main() {
 gzopen()
 ; return 0; }
 EOF
-if { (eval echo configure:14042: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:14044: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -14056,17 +14058,17 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   
     ac_safe=`echo "zlib.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for zlib.h""... $ac_c" 1>&6
-echo "configure:14060: checking for zlib.h" >&5
+echo "configure:14062: checking for zlib.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 14065 "configure"
+#line 14067 "configure"
 #include "confdefs.h"
 #include <zlib.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:14070: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:14072: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -14084,12 +14086,12 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   
       echo $ac_n "checking if zlib version >= 1.1.3""... $ac_c" 1>&6
-echo "configure:14088: checking if zlib version >= 1.1.3" >&5
+echo "configure:14090: checking if zlib version >= 1.1.3" >&5
       if test "$cross_compiling" = yes; then
   echo "$ac_t""no" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 14093 "configure"
+#line 14095 "configure"
 #include "confdefs.h"
 
 #include "confdefs.h"
@@ -14103,7 +14105,7 @@ int main() {
 #endif
 }
 EOF
-if { (eval echo configure:14107: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:14109: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   echo "$ac_t""yes" 1>&6
           have_zlib=yes
@@ -14132,12 +14134,28 @@ fi
 EOF
 
     LIBS="-lz ${LIBS}"
+  else
+    if test -f src/extra/zlib/Makefile ; then
+      echo "checking we will build zlib for you" 1>&6
+echo "configure:14141: checking we will build zlib for you" >&5
+    else
+      { echo "configure: error: neither zlib nor its sources were found" 1>&2; exit 1; }
+    fi
   fi
+  
+
+if test "${have_zlib}" = no; then
+  BUILD_ZLIB_TRUE=
+  BUILD_ZLIB_FALSE='#'
+else
+  BUILD_ZLIB_TRUE='#'
+  BUILD_ZLIB_FALSE=
+fi
 
 
 ## POSIX times.
 echo $ac_n "checking whether leap seconds are treated according to POSIX""... $ac_c" 1>&6
-echo "configure:14141: checking whether leap seconds are treated according to POSIX" >&5
+echo "configure:14159: checking whether leap seconds are treated according to POSIX" >&5
 if eval "test \"`echo '$''{'r_cv_sys_posix_leapseconds'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -14145,7 +14163,7 @@ else
   r_cv_sys_posix_leapseconds=yes
 else
   cat > conftest.$ac_ext <<EOF
-#line 14149 "configure"
+#line 14167 "configure"
 #include "confdefs.h"
 
 #include <stdlib.h>
@@ -14163,7 +14181,7 @@ int main () {
   if(tm->tm_sec == 0) exit(1); else exit(0);
 }
 EOF
-if { (eval echo configure:14167: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:14185: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   r_cv_sys_posix_leapseconds=no
 else
@@ -14191,12 +14209,12 @@ if test "${want_R_profiling}" = yes; then
   for ac_func in setitimer
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:14195: checking for $ac_func" >&5
+echo "configure:14213: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 14200 "configure"
+#line 14218 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -14219,7 +14237,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:14223: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:14241: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -14261,7 +14279,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:14265: checking for $ac_word" >&5
+echo "configure:14283: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_R_PRINTCMD'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -14300,7 +14318,7 @@ EOF
 # Extract the first word of "paperconf", so it can be a program name with args.
 set dummy paperconf; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:14304: checking for $ac_word" >&5
+echo "configure:14322: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PAPERCONF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -14761,6 +14779,8 @@ s%@use_tcltk@%$use_tcltk%g
 s%@BITMAP_LIBS@%$BITMAP_LIBS%g
 s%@BUILD_XDR_TRUE@%$BUILD_XDR_TRUE%g
 s%@BUILD_XDR_FALSE@%$BUILD_XDR_FALSE%g
+s%@BUILD_ZLIB_TRUE@%$BUILD_ZLIB_TRUE%g
+s%@BUILD_ZLIB_FALSE@%$BUILD_ZLIB_FALSE%g
 s%@R_PROFILING@%$R_PROFILING%g
 s%@R_PRINTCMD@%$R_PRINTCMD%g
 s%@PAPERCONF@%$PAPERCONF%g
