make use of tclConfig.sh etc to set the include paths (needed for activeTcl on MacOS X)
git-svn-id: https://svn.r-project.org/R/trunk@44778 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -44032,20 +44032,164 @@ if test -z "${TCLTK_CPPFLAGS}"; then
     found_tcl_h=no
     if test -n "${TCL_CONFIG}"; then
       . ${TCL_CONFIG}
-      ## Look for tcl.h in
-      ##   ${TCL_PREFIX}/include/tcl${TCL_VERSION}
-      ##   ${TCL_PREFIX}/include
-      ## Also look in
-      ##   ${TCL_PREFIX}/include/tcl${TCL_VERSION}/generic
-      ## to deal with current FreeBSD layouts.  These also link the real
-      ## thing to the version subdir, but the link cannot be used as it
-      ## fails to include 'tclDecls.h' which is not linked.  Hence we
-      ## must look for the real thing first.  Argh ...
-      for dir in \
-          ${TCL_PREFIX}/include/tcl${TCL_VERSION}/generic \
-          ${TCL_PREFIX}/include/tcl${TCL_VERSION} \
-          ${TCL_PREFIX}/include; do
-        as_ac_Header=`echo "ac_cv_header_${dir}/tcl.h" | $as_tr_sh`
+      ## TCL_INCLUDE_SPEC (if set) is what we want.
+      if test -n ${TCL_INCLUDE_SPEC} ; then
+        r_save_CPPFLAGS="${CPPFLAGS}"
+	CPPFLAGS="${CPPFLAGS} ${TCL_INCLUDE_SPEC}"
+	if test "${ac_cv_header_tcl_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for tcl.h" >&5
+echo $ECHO_N "checking for tcl.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_tcl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_tcl_h" >&5
+echo "${ECHO_T}$ac_cv_header_tcl_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking tcl.h usability" >&5
+echo $ECHO_N "checking tcl.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <tcl.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking tcl.h presence" >&5
+echo $ECHO_N "checking tcl.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tcl.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: tcl.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: tcl.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tcl.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: tcl.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: tcl.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: tcl.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tcl.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: tcl.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tcl.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: tcl.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tcl.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: tcl.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tcl.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: tcl.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tcl.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: tcl.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ----------------------------------- ##
+## Report this to r-bugs@R-project.org ##
+## ----------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for tcl.h" >&5
+echo $ECHO_N "checking for tcl.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_tcl_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_tcl_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_tcl_h" >&5
+echo "${ECHO_T}$ac_cv_header_tcl_h" >&6; }
+
+fi
+if test $ac_cv_header_tcl_h = yes; then
+  TCLTK_CPPFLAGS="${TCL_INCLUDE_SPEC}"
+			 found_tcl_h=yes
+			 break
+fi
+
+
+	CPPFLAGS="${r_save_CPPFLAGS}"
+      fi
+      if test "${found_tcl_h}" = no; then
+	## Look for tcl.h in
+	##   ${TCL_PREFIX}/include/tcl${TCL_VERSION}
+	##   ${TCL_PREFIX}/include
+	## Also look in
+	##   ${TCL_PREFIX}/include/tcl${TCL_VERSION}/generic
+	## to deal with current FreeBSD layouts.  These also link the real
+	## thing to the version subdir, but the link cannot be used as it
+	## fails to include 'tclDecls.h' which is not linked.  Hence we
+	## must look for the real thing first.  Argh ...
+	for dir in \
+	    ${TCL_PREFIX}/include/tcl${TCL_VERSION}/generic \
+	    ${TCL_PREFIX}/include/tcl${TCL_VERSION} \
+	    ${TCL_PREFIX}/include; do
+	  as_ac_Header=`echo "ac_cv_header_${dir}/tcl.h" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
   { echo "$as_me:$LINENO: checking for ${dir}/tcl.h" >&5
 echo $ECHO_N "checking for ${dir}/tcl.h... $ECHO_C" >&6; }
@@ -44180,12 +44324,13 @@ echo "${ECHO_T}$ac_res" >&6; }
 fi
 if test `eval echo '${'$as_ac_Header'}'` = yes; then
   TCLTK_CPPFLAGS="-I${dir}"
-                         found_tcl_h=yes
-                         break
+			   found_tcl_h=yes
+			   break
 fi
 
 
-      done
+	done
+      fi
     fi
     if test "${found_tcl_h}" = no; then
       { echo "$as_me:$LINENO: checking for tcl.h" >&5
@@ -44231,27 +44376,171 @@ echo "${ECHO_T}$r_cv_header_tcl_h" >&6; }
     found_tk_h=no
     if test -n "${TK_CONFIG}"; then
       . ${TK_CONFIG}
-      ## Look for tk.h in
-      ##   ${TK_PREFIX}/include/tk${TK_VERSION}
-      ##   ${TK_PREFIX}/include
-      ## Also look in
-      ##   ${TK_PREFIX}/include/tcl${TK_VERSION}
-      ## to compensate for Debian madness ...
-      ## Also look in
-      ##   ${TK_PREFIX}/include/tk${TK_VERSION}/generic
-      ## to deal with current FreeBSD layouts.  See above for details.
-      ##
-      ## As the AC_CHECK_HEADER test tries including the header file and
-      ## tk.h includes tcl.h and X11/Xlib.h, we need to change CPPFLAGS
-      ## for the check.
-      r_save_CPPFLAGS="${CPPFLAGS}"
-      CPPFLAGS="${CPPFLAGS} ${TK_XINCLUDES} ${TCLTK_CPPFLAGS}"
-      for dir in \
-          ${TK_PREFIX}/include/tk${TK_VERSION}/generic \
-          ${TK_PREFIX}/include/tk${TK_VERSION} \
-          ${TK_PREFIX}/include/tcl${TK_VERSION} \
-          ${TK_PREFIX}/include; do
-        as_ac_Header=`echo "ac_cv_header_${dir}/tk.h" | $as_tr_sh`
+      ## TK_INCLUDE_SPEC (if set) is what we want.
+      if test -n ${TK_INCLUDE_SPEC} ; then
+        r_save_CPPFLAGS="${CPPFLAGS}"
+	CPPFLAGS="${CPPFLAGS} ${TCLTK_CPPFLAGS} ${TK_XINCLUDES} ${TK_INCLUDE_SPEC}"
+	if test "${ac_cv_header_tk_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for tk.h" >&5
+echo $ECHO_N "checking for tk.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_tk_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_tk_h" >&5
+echo "${ECHO_T}$ac_cv_header_tk_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking tk.h usability" >&5
+echo $ECHO_N "checking tk.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <tk.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking tk.h presence" >&5
+echo $ECHO_N "checking tk.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tk.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: tk.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: tk.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tk.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: tk.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: tk.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: tk.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tk.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: tk.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tk.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: tk.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tk.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: tk.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tk.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: tk.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tk.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: tk.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ----------------------------------- ##
+## Report this to r-bugs@R-project.org ##
+## ----------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for tk.h" >&5
+echo $ECHO_N "checking for tk.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_tk_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_tk_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_tk_h" >&5
+echo "${ECHO_T}$ac_cv_header_tk_h" >&6; }
+
+fi
+if test $ac_cv_header_tk_h = yes; then
+  TCLTK_CPPFLAGS="${TCLTK_CPPFLAGS} ${TK_INCLUDE_SPEC}"
+			 found_tk_h=yes
+			 break
+fi
+
+
+	CPPFLAGS="${r_save_CPPFLAGS}"
+      fi
+      if test "${found_tk_h}" = no; then
+	## Look for tk.h in
+	##   ${TK_PREFIX}/include/tk${TK_VERSION}
+	##   ${TK_PREFIX}/include
+	## Also look in
+	##   ${TK_PREFIX}/include/tcl${TK_VERSION}
+	## to compensate for Debian madness ...
+	## Also look in
+	##   ${TK_PREFIX}/include/tk${TK_VERSION}/generic
+	## to deal with current FreeBSD layouts.  See above for details.
+	##
+	## As the AC_CHECK_HEADER test tries including the header file and
+	## tk.h includes tcl.h and X11/Xlib.h, we need to change CPPFLAGS
+	## for the check.
+	r_save_CPPFLAGS="${CPPFLAGS}"
+	CPPFLAGS="${CPPFLAGS} ${TK_XINCLUDES} ${TCLTK_CPPFLAGS}"
+	for dir in \
+	    ${TK_PREFIX}/include/tk${TK_VERSION}/generic \
+	    ${TK_PREFIX}/include/tk${TK_VERSION} \
+	    ${TK_PREFIX}/include/tcl${TK_VERSION} \
+	    ${TK_PREFIX}/include; do
+	  as_ac_Header=`echo "ac_cv_header_${dir}/tk.h" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
   { echo "$as_me:$LINENO: checking for ${dir}/tk.h" >&5
 echo $ECHO_N "checking for ${dir}/tk.h... $ECHO_C" >&6; }
@@ -44386,13 +44675,14 @@ echo "${ECHO_T}$ac_res" >&6; }
 fi
 if test `eval echo '${'$as_ac_Header'}'` = yes; then
   TCLTK_CPPFLAGS="${TCLTK_CPPFLAGS} -I${dir}"
-                         found_tk_h=yes
-                         break
+			   found_tk_h=yes
+			   break
 fi
 
 
-      done
-      CPPFLAGS="${r_save_CPPFLAGS}"
+	done
+	CPPFLAGS="${r_save_CPPFLAGS}"
+      fi
     fi
     if test "${found_tk_h}" = no; then
       { echo "$as_me:$LINENO: checking for tk.h" >&5
