use -fpic rather than -fPIC where possible. FCPICFLAGS on Darwin needs to be -fno-common
git-svn-id: https://svn.r-project.org/R/trunk@37033 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29670,14 +29670,39 @@ fi
 
 ## Step 2.  GNU compilers.
 if test "${GCC}" = yes; then
-  cpicflags="-fPIC"
+  case "${host_cpu}" in
+## Sparc has only an 8k global object table, 1024 entries on 64-bit.
+## PowerPC has 32k, not enough on ppc64 for the ca6200 entries in libR.so
+## The only other platform where this is said to matter is m68k, which
+## has 32k and so can use -fpic.
+    sparc*|ppc64)
+      cpicflags="-fPIC"
+      ;;
+    *)
+      cpicflags="-fpic"
+      ;;
+  esac
   shlib_ldflags="-shared"
 fi
 if test "${G77}" = yes; then
-  fpicflags="-fPIC"
+  case "${host_cpu}" in
+    sparc*|ppc64)
+      fpicflags="-fPIC"
+      ;;
+    *)
+      fpicflags="-fpic"
+      ;;
+  esac
 fi
 if test "${GXX}" = yes; then
-  cxxpicflags="-fPIC"
+  case "${host_cpu}" in
+    sparc*|ppc64)
+      cxxpicflags="-fPIC"
+      ;;
+    *)
+      cxxpicflags="-fpic"
+      ;;
+  esac
   shlib_cxxldflags="-shared"
 fi
 
@@ -29785,7 +29810,7 @@ fi ;;
     case  "${CC}" in
       ## Intel compiler
       *icc)
-        cpicflags="-fPIC"
+        cpicflags="-fpic"
         ;;
       ## Portland Group (information from Jennifer Lai)
       *pgcc)
@@ -29888,7 +29913,7 @@ fi
     case  "${F77}" in
       ## Intel compilers
       *ifc|*ifort)
-        fpicflags="-fPIC"
+        fpicflags="-fpic"
         ;;
       ## Portland Group
       *pgf77)
@@ -29898,7 +29923,7 @@ fi
     case  "${CXX}" in
       ## Intel compilers
       *icpc|*icc)
-        cxxpicflags="-fPIC"
+        cxxpicflags="-fpic"
         ;;
       ## Portland Group
       *pgCC)
@@ -29936,6 +29961,8 @@ fi
     shlib_ldflags="-shared"
     ;;
   solaris*)
+## SPARC has only an 8k global object table, 1024 entries on 64-bit,
+## so need PIC not pic.  They are the same on other Solaris platforms.
     shlib_ldflags="-G"
     shlib_cxxldflags="-G"
     if test "${GCC}" = yes; then
@@ -30002,8 +30029,8 @@ if test -z "${CPICFLAGS}"; then
     *)
       { echo "$as_me:$LINENO: WARNING: I could not determine CPICFLAGS." >&5
 echo "$as_me: WARNING: I could not determine CPICFLAGS." >&2;}
-      { { echo "$as_me:$LINENO: error: See the file INSTALL for more information." >&5
-echo "$as_me: error: See the file INSTALL for more information." >&2;}
+      { { echo "$as_me:$LINENO: error: See the file doc/html/R-admin.html for more information." >&5
+echo "$as_me: error: See the file doc/html/R-admin.html for more information." >&2;}
    { (exit 1); exit 1; }; }
       ;;
   esac
@@ -30017,8 +30044,8 @@ if test -z "${FPICFLAGS}"; then
     *)
       { echo "$as_me:$LINENO: WARNING: I could not determine FPICFLAGS." >&5
 echo "$as_me: WARNING: I could not determine FPICFLAGS." >&2;}
-      { { echo "$as_me:$LINENO: error: See the file INSTALL for more information." >&5
-echo "$as_me: error: See the file INSTALL for more information." >&2;}
+      { { echo "$as_me:$LINENO: error: See the file doc/html/R-admin.html for more information." >&5
+echo "$as_me: error: See the file doc/html/R-admin.html for more information." >&2;}
    { (exit 1); exit 1; }; }
       ;;
   esac
@@ -30050,8 +30077,8 @@ fi
 if test -z "${SHLIB_LDFLAGS}"; then
   { echo "$as_me:$LINENO: WARNING: I could not determine SHLIB_LDFLAGS." >&5
 echo "$as_me: WARNING: I could not determine SHLIB_LDFLAGS." >&2;}
-  { { echo "$as_me:$LINENO: error: See the file INSTALL for more information." >&5
-echo "$as_me: error: See the file INSTALL for more information." >&2;}
+  { { echo "$as_me:$LINENO: error: See the file doc/html/R-admin.html for more information." >&5
+echo "$as_me: error: See the file doc/html/R-admin.html for more information." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -42936,7 +42963,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:42939:" \
+echo "$as_me:42966:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -43229,7 +43256,24 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 : ${SHLIB_FCLDFLAGS="${SHLIB_LDFLAGS}"}
 
 
+
+## Look for FCPICFLAGS
+## Debian in their wisdom have f95 as a link to gfortran, so
+## use this to pick out gfortran (even though it is unreliable).
+if test "${ac_cv_fc_compiler_gnu}" = yes; then
+  case "${host_cpu}" in
+    sparc*|ppc64)
+      fcpicflags="-fPIC"
+      ;;
+    *)
+      fcpicflags="-fpic"
+      ;;
+  esac
+fi
 case "${host_os}" in
+  darwin*)
+    fcpicflags="-fno-common"
+    ;;
   hpux*)
     case "${FC}" in
       f90)
@@ -43238,15 +43282,10 @@ case "${host_os}" in
     esac
     ;;
   linux*)
-    ## Debian in their wisdom have f95 as a link to gfortran, so
-    ## use this to pick out gfortran (even though it is unreliable).
-    if test "${ac_cv_fc_compiler_gnu}" = yes; then
-      fcpicflags="-fPIC"
-    fi
     case  "${FC}" in
       ## Intel compilers: probably get identified as GNU, but make sure.
       *ifc|*ifort)
-        fcpicflags="-fPIC"
+        fcpicflags="-fpic"
         ;;
       ## Portland Group
       *pgf95)
