make not finding IEEE 754 support a configuration error
git-svn-id: https://svn.r-project.org/R/trunk@29405 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35623,6 +35623,10 @@ cat >>confdefs.h <<\_ACEOF
 #define IEEE_754 1
 _ACEOF
 
+else
+  { { echo "$as_me:$LINENO: error: IEEE 754 floating-point arithmetic is required" >&5
+echo "$as_me: error: IEEE 754 floating-point arithmetic is required" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
