don't allow f2c on 64-bit platforms as integer=long
git-svn-id: https://svn.r-project.org/R/trunk@30834 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26565,6 +26565,11 @@ fi
 
 
 else
+  if test ${ac_cv_sizeof_long} -gt 4 ; then
+    { { echo "$as_me:$LINENO: error: Cannot use f2c on a > 32-bit machine" >&5
+echo "$as_me: error: Cannot use f2c on a > 32-bit machine" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
 
 if test "${r_cv_f2c_flibs+set}" = set; then
