remove support for --without-iconv
git-svn-id: https://svn.r-project.org/R/trunk@48902 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1796,7 +1796,6 @@ Optional Packages:
                           (0/1/2) [0]
   --with-recommended-packages
                           use/install recommended R packages [yes]
-  --with-iconv            use iconv library [yes]
   --with-ICU              use ICU library [yes]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -2977,21 +2976,6 @@ fi
 
 else
   use_recommended_packages=yes
-fi
-
-
-## Iconv.
-
-# Check whether --with-iconv was given.
-if test "${with_iconv+set}" = set; then
-  withval=$with_iconv; if test "${withval}" = no; then
-  use_iconv=no
-else
-  use_iconv=yes
-fi
-
-else
-  use_iconv=yes
 fi
 
 
@@ -8215,13 +8199,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:8218: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:8202: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:8221: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:8205: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:8224: output\"" >&5)
+  (eval echo "\"\$as_me:8208: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -9431,7 +9415,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 9434 "configure"' > conftest.$ac_ext
+  echo '#line 9418 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11882,11 +11866,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11885: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11869: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11889: \$? = $ac_status" >&5
+   echo "$as_me:11873: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12221,11 +12205,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12224: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12208: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12228: \$? = $ac_status" >&5
+   echo "$as_me:12212: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12326,11 +12310,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12329: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12313: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12333: \$? = $ac_status" >&5
+   echo "$as_me:12317: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12381,11 +12365,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12384: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12368: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12388: \$? = $ac_status" >&5
+   echo "$as_me:12372: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15137,7 +15121,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 15140 "configure"
+#line 15124 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15233,7 +15217,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 15236 "configure"
+#line 15220 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17245,11 +17229,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17248: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17232: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17252: \$? = $ac_status" >&5
+   echo "$as_me:17236: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17344,11 +17328,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17347: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17331: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17351: \$? = $ac_status" >&5
+   echo "$as_me:17335: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17396,11 +17380,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17399: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17383: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17403: \$? = $ac_status" >&5
+   echo "$as_me:17387: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18804,11 +18788,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18807: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18791: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18811: \$? = $ac_status" >&5
+   echo "$as_me:18795: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18903,11 +18887,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18906: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18890: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18910: \$? = $ac_status" >&5
+   echo "$as_me:18894: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18955,11 +18939,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18958: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18942: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18962: \$? = $ac_status" >&5
+   echo "$as_me:18946: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27664,7 +27648,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_verb"
-(eval echo $as_me:27667: \"$ac_link\") >&5
+(eval echo $as_me:27651: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -27747,7 +27731,7 @@ _ACEOF
 # flags.
 r_save_CFLAGS=$CFLAGS
 CFLAGS="$CFLAGS $r_cv_prog_c_v"
-(eval echo $as_me:27750: \"$ac_link\") >&5
+(eval echo $as_me:27734: \"$ac_link\") >&5
 r_c_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$r_c_v_output" >&5
 CFLAGS=$r_save_CFLAGS
@@ -38634,7 +38618,6 @@ fi
 ### * Checks for system services.
 
 ## iconv headers and function.
-if test "${use_iconv}" = yes; then
 
 for ac_header in iconv.h
 do
@@ -39107,22 +39090,19 @@ _ACEOF
 
 fi
 
-  if test "$r_cv_iconv_latin1" != yes; then
-    { { echo "$as_me:$LINENO: error: --with-iconv=yes (default) and a suitable iconv is not available" >&5
-echo "$as_me: error: --with-iconv=yes (default) and a suitable iconv is not available" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
-else
-    { echo "$as_me:$LINENO: WARNING: --with-iconv=no is deprecated and will be withdrawn shortly" >&5
-echo "$as_me: WARNING: --with-iconv=no is deprecated and will be withdrawn shortly" >&2;}
-fi
-
-## support for MBCS
+## on Windows we supply iconv ourselves
 case "${host_os}" in
   mingw*)
     r_cv_iconv_latin1=yes
     ;;
 esac
+if test "$r_cv_iconv_latin1" != yes; then
+  { { echo "$as_me:$LINENO: error: a suitable iconv is not available" >&5
+echo "$as_me: error: a suitable iconv is not available" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+## support for MBCS
 
 if test "$want_mbcs_support" = yes ; then
   if test "$r_cv_iconv_latin1" != yes ; then
@@ -48078,11 +48058,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48081: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48061: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:48085: \$? = $ac_status" >&5
+   echo "$as_me:48065: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -48177,11 +48157,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48180: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48160: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48184: \$? = $ac_status" >&5
+   echo "$as_me:48164: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -48229,11 +48209,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:48232: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:48212: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:48236: \$? = $ac_status" >&5
+   echo "$as_me:48216: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -62107,15 +62087,6 @@ if test -z "${r_capabilities}"; then
   r_capabilities="TIFF"
 else
   r_capabilities="${r_capabilities}${separator}TIFF"
-fi
-fi
-if test "${r_cv_iconv_latin1}" = yes; then
-  separator=", "
-test -z "${separator}" && separator=" "
-if test -z "${r_capabilities}"; then
-  r_capabilities="iconv"
-else
-  r_capabilities="${r_capabilities}${separator}iconv"
 fi
 fi
 if test "${want_mbcs_support}" = yes; then
