Updated.
git-svn-id: https://svn.r-project.org/R/trunk@19546 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15569,6 +15569,62 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+    ac_safe=`echo "-mieee-fp" | sed 'y%./+-:=%__p___%'`
+echo "$as_me:$LINENO: checking whether ${F77-f77} accepts -mieee-fp" >&5
+echo $ECHO_N "checking whether ${F77-f77} accepts -mieee-fp... $ECHO_C" >&6
+if eval "test \"\${r_cv_prog_f77_flag_${ac_safe}+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+
+r_save_FFLAGS="${FFLAGS}"
+FFLAGS="${FFLAGS} -mieee-fp"
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "r_cv_prog_f77_flag_${ac_safe}=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "r_cv_prog_f77_flag_${ac_safe}=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+FFLAGS="${r_save_FFLAGS}"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+
+if eval "test \"`echo '$r_cv_prog_f77_flag_'$ac_safe`\" = yes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  R_XTRA_FFLAGS="${R_XTRA_FFLAGS} -mieee-fp"
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 
 ac_safe=`echo "-mieee-fp" | sed 'y%./+-:=%__p___%'`
 echo "$as_me:$LINENO: checking whether ${CXX-c++} accepts -mieee-fp" >&5
