Added new make target distcheck.
git-svn-id: https://svn.r-project.org/R/trunk@78031 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -221,6 +221,53 @@ distdir: $(DISTFILES) vignettes
 	  cp library/$${d}/doc/*.pdf $(distdir)/src/library/$${d}/inst/doc; \
 	done
 	@(cd $(distdir); tools/link-recommended)
+distcheck: distcheck-unix
+distcheck-unix: dist
+	distname=`$(srcdir)/tools/GETDISTNAME`; \
+	dirname=`$(ECHO) $${distname} | sed -e s/_.*//`; \
+	rm -Rf $${dirname}; \
+	$(R_GZIPCMD) -d -c $${distname}.tar.gz | $(TAR) -x -f -; \
+	chmod u+w $${dirname}; \
+	mkdir $${dirname}/_build $${dirname}/_inst; \
+	test -d $${dirname}/_build || exit 0; \
+	dc_install_base=`cd $${dirname}/_inst && pwd` \
+	  && save__cwd=`pwd` \
+	  && cd $${dirname}/_build \
+	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
+	  && $(MAKE) \
+	  && $(MAKE) check-all \
+	  && $(MAKE) install \
+	  && $(MAKE) uninstall \
+	  && $(MAKE) distuninstallcheck_dir="$$dc_install_base" \
+	        distuninstallcheck \
+	  && $(MAKE) dist \
+	  && rm -f $${distname}.tar.gz \
+	  && $(MAKE) distcleancheck \
+	  && cd "$$save__cwd" \
+	  || exit 1; \
+	rm -Rf $${dirname}; \
+	$(ECHO) "$${distname}.tar.gz ready for distribution" \
+distcheck-win:
+distuninstallcheck:
+	@test -n '$(distuninstallcheck_dir)' || { \
+	  echo 'ERROR: trying to run $@ with an empty' \
+	       '$$(distuninstallcheck_dir)' >&2; \
+	  exit 1; \
+	}; \
+	cd '$(distuninstallcheck_dir)' || { \
+	  $(ECHO) 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
+	  exit 1; \
+	}; \
+	test `find . -type f -print | wc -l` -eq 0 || \
+	  { $(ECHO) "ERROR: files left after uninstall:" ; \
+	    `find . -type f -print`; \
+	    exit 1; } >&2
+distcleancheck: distclean
+	@test `find . -type f -print | wc -l` -eq 0 || \
+	  { $(ECHO) "ERROR: files left in build directory after distclean:" ; \
+	    `find . -type f -print`; \
+	    exit 1; } >&2
+
 
 info pdf:
 	-@(cd doc && $(MAKE) $@)
