changes for R-script INSTALL
git-svn-id: https://svn.r-project.org/R/trunk@47504 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/gnuwin32/Makefile b/src/gnuwin32/Makefile
--- a/src/gnuwin32/Makefile
+++ b/src/gnuwin32/Makefile
@@ -570,25 +570,13 @@ unpack-recommended:
 clean-recommended:
 	@for i in ${R_PKGS_RECOMMENDED_SOURCES} ; do $(RM) -r ../library/$${i} ; done
 
-ifeq ($(strip $(HELP)),YES)
-ifeq ($(strip $(WINHELP)),CHM)
-DOCSTYPE=all
-else
-DOCSTYPE=normal
-endif
-else
-DOCSTYPE=none
-endif
-
 recommended: unpack-recommended
 	@$(ECHO) "--- Making recommended packages"
 ifeq ($(strip $(BUILD)),CROSS)
-	@for p in $(R_PKGS_RECOMMENDED_SOURCES); do \
-          $(R_EXE) CMD $(PERL) XINSTALL --unsafe -l $(RHOME)/library --docs=normal ../library/$${p} || exit 1; \
-        done
+	@echo 'ERROR: cross-builing of recommended packages is currently not supported'
 else
 	@for p in $(R_PKGS_RECOMMENDED_SOURCES); do \
-	  $(RHOME)/bin/rcmd.exe INSTALL --unsafe -l $(RHOME)/library ../library/$${p} --docs=$(DOCSTYPE) || exit 1; \
+	  $(RHOME)/bin/rcmd.exe INSTALL --unsafe -l $(RHOME)/library ../library/$${p} || exit 1; \
 	done
 endif
 
