Barf on illegal Rd file names.
git-svn-id: https://svn.r-project.org/R/trunk@8749 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/build b/src/scripts/build
--- a/src/scripts/build
+++ b/src/scripts/build
@@ -2,7 +2,7 @@
 #
 # ${R_HOME}/bin/build
 
-revision='$Revision: 1.14 $'
+revision='$Revision: 1.15 $'
 version=`set - ${revision}; echo ${2}`
 version="R package builder ${version}
 
@@ -226,6 +226,15 @@ buildpkg () {
     find man -name "*.[Rr]d" -print | sort > ${all_file}
     Rdfiles=`cat ${all_file}`
     if test -n "${Rdfiles}"; then
+      badfiles=`grep "<" ${all_file}`
+      if test -n "${badfiles}"; then
+	result "ERROR"
+	echo "Cannot handle Rd file names containing \`<'."
+	echo "These are not legal file names on all R platforms."
+	echo "Please rename the following files and try again."
+	echo "${badfiles}"
+	exit 1
+      fi
       any=
       for tag in name alias title description keyword; do
 	rm -f ${tag_file} 2>/dev/null
