This commit was manufactured by cvs2svn to create tag 'R-1-4-1'.
git-svn-id: https://svn.r-project.org/R/tags/R-1-4-1@18029 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.82 $'
+revision='$Revision: 1.82.2.1 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -46,6 +46,7 @@ Options:
 Report bugs to <r-bugs@r-project.org>."
 
 R_VERSION='@VERSION@'
+GETWD='@GETWD@'
 INSTALL='@INSTALL@'
 MAKE=${MAKE-'@MAKE@'}
 NO_PERL5=@NO_PERL5@
@@ -174,10 +175,15 @@ fi
 
 if test -d ${lib} -a -w ${lib} || mkdir ${lib} 2> /dev/null; then
   lib=`cd ${lib}; pwd`
-  ## FIXME: Remove eventually.
+  ## <FIXME>
+  ## Remove eventually.
   rm -f ${lib}/LibIndex
   ## </FIXME>
+  ## <FIXME>
+  ## We should only do this if at least one package gets installed: if
+  ## e.g. builddir is srcdir there will be none.
   cp ${R_HOME}/doc/html/R.css ${lib}
+  ## </FIXME>
 else
   echo "ERROR: cannot write to or create directory \`${lib}'"
   exit 2
@@ -227,7 +233,13 @@ do_install () {
     fi
   fi
 
-  mkdir -p ${lib}/${pkg} || exit 3
+  mkdir -p ${lib}/${pkg} || exit 2
+
+  ## Make sure we do not attempt installing to srcdir.
+  if test "`cd ${lib}/${pkg} && ${GETWD}`" = "`${GETWD}`"; then
+    echo "cannot install to srcdir"
+    exit 3
+  fi  
 
   ## Figure out whether this is a source or binary package.
   if grep "^Built:" DESCRIPTION >/dev/null ; then
