Cannot exit from subshell.
git-svn-id: https://svn.r-project.org/R/trunk@16443 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.73 $'
+revision='$Revision: 1.74 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -355,8 +355,12 @@ do_install () {
       export R_PROFILE
       (echo " .lib.loc <- c(\"${lib}\", .lib.loc)";
         cat ${lib}/${pkg}/R/${pkg};
-        echo "rm(.lib.loc)") | ${R_HOME}/bin/R --save --silent ${save_args}\
-          || (echo "Execution of package source for ${pkg} failed"; exit 1)
+        echo "rm(.lib.loc)") | \
+	${R_HOME}/bin/R --save --silent ${save_args}
+      if test ${?} -ne 0; then
+        echo "ERROR: execution of package source for ${pkg} failed"
+	exit 1
+      fi
       mv .RData ${lib}/${pkg}/R/all.rda
       mv ${lib}/${pkg}/R/${pkg} ${lib}/${pkg}/R/${pkg}.R
       cat ${R_HOME}/share/R/firstlib.R > ${lib}/${pkg}/R/${pkg}
