Exit on configure error.
git-svn-id: https://svn.r-project.org/R/trunk@8124 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.30 $'
+revision='$Revision: 1.31 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}"
 
@@ -184,6 +184,10 @@ do_install () {
 
   if test -x ./configure ; then
     ./configure ${configure_args}
+    if test ${?} -ne 0; then
+      echo "ERROR: Configuration failed for package \`${pkg}'"
+      exit 4
+    fi
   fi
 
   if test -d src; then
@@ -209,7 +213,7 @@ do_install () {
     fi
     if ${error}; then
       echo "ERROR: Compilation failed for package \`${pkg}'"
-      exit 4
+      exit 5
     fi
     if ${debug}; then set +x; fi
   fi
