Check exit status of R_EXE calls for installing meta-data.
git-svn-id: https://svn.r-project.org/R/branches/R-1-7-patches@24203 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.115 $'
+revision='$Revision: 1.115.2.1 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -295,6 +295,12 @@ do_install_source () {
   fi  
   stars="**"
 
+  ## <FIXME>
+  ## Should really test for existence of DESCRIPTION file here, and
+  ## abort if there is none.  Once we do this, remove the existence test
+  ## when installing DESCRIPTION.
+  ## </FIXME>
+
   if ${use_configure} && test -x ./configure ; then
     eval ${configure_vars} ./configure ${configure_args}
     if test ${?} -ne 0; then
@@ -396,6 +402,7 @@ do_install_source () {
     ## exclude everything in @file{.Rbuildignore}, but that's another
     ## story ...)
     cp -r inst/* "${R_PACKAGE_DIR}"
+    ## </FIXME>
   fi
 
   case ${save} in
@@ -414,7 +421,7 @@ do_install_source () {
   if ${R_SAVE_IMAGE}; then
     message "save image"
     if test -f NAMESPACE; then
-      echo "ERROR: cannot use --save if package has NAMESPACE yet"
+      echo "ERROR: cannot (yet) use '--save' if package has NAMESPACE"
       exit 1
     fi
     ## <NOTE>
@@ -458,6 +465,10 @@ do_install_source () {
     ## </FIXME>
     echo ".installPackageDescription(\".\", \"${R_PACKAGE_DIR}\")" | \
       R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null 2>&1
+    if test ${?} -ne 0; then
+      echo "ERROR: installing package DESCRIPTION failed"
+      exit 1
+    fi
   fi
 
   if test -d man; then
@@ -511,6 +522,10 @@ do_install_source () {
 
   echo ".installPackageIndices(\".\", \"${R_PACKAGE_DIR}\")" | \
     R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null 2>&1
+  if test ${?} -ne 0; then
+    echo "ERROR: installing package indices failed"
+    exit 1
+  fi
 
   if ${clean}; then
     if test -x ./cleanup ; then
