Signal error for now when installing package with --save and package has a NAMESPACE file.
git-svn-id: https://svn.r-project.org/R/trunk@23245 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.108 $'
+revision='$Revision: 1.109 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -399,6 +399,10 @@ do_install_source () {
 
   if ${R_SAVE_IMAGE}; then
     message "save image"
+    if test -f NAMESPACE; then
+      echo "ERROR: cannot use --save if package has NAMESPACE yet"
+	exit 1
+    fi
     ## <NOTE>
     ## We want R to run as quietly as possible when creating the save
     ## image.  But this is tricky: sending options(echo=FALSE) to R via
