modifications to allow packages to be installed with version numbers
git-svn-id: https://svn.r-project.org/R/trunk@23520 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.111 $'
+revision='$Revision: 1.112 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -40,6 +40,11 @@ Options:
   -l, --library=LIB	install packages to library tree LIB
       --no-configure    do not use the package's configure script
       --no-docs		do not build and install documentation
+      --with-package-versions	Allow for multiple versions of the
+				same package.
+      --check-R-version=true	For binary packages, make sure that the R
+                                 version matches the R version the package
+                                 was built under.
       --use-zip-data	collect data files in zip archive
       --use-zip-help	collect help and examples into zip archives
       --use-zip		combine '--use-zip-data' and '--use-zip-help'
@@ -143,7 +148,8 @@ use_zip_data=
 use_zip_help=
 configure_args=
 configure_vars=
-
+package_versions=false
+check_R_version=true
 save="CHECK"
 save_args="--no-site-file --no-init-file";
 
@@ -163,6 +169,10 @@ while test -n "${1}"; do
       save=false ;;
     -d|--debug)
       debug=true ;;
+    --with-package-versions)
+      package_versions=true ;;
+    --check-R-version=*)
+      check_R_version=`echo "${1}" | sed -e 's/[^=]*=//' | awk '{print(tolower($0))}'`;;
     --no-configure)
       use_configure=false ;;
     --no-docs)
@@ -258,8 +268,11 @@ fi
 
 do_install_binary () {
   pkg="${1}"
-  message "Installing *binary* package '${pkg}' ..."
-  cp -r . "${lib}/${pkg}"
+  R_PACKAGE_DIR="${2}"
+  R_FULL_PKG="${3}"
+
+  message "Installing *binary* package '${R_FULL_PKG}' ..."
+  cp -r . "${R_PACKAGE_DIR}"
 }
 
 ### 
@@ -267,17 +280,20 @@ do_install_binary () {
 
 do_install_source () {
   pkg="${1}"
-  message "Installing *source* package '${pkg}' ..."
   stars="**"
 
   ## Make the destination directories available to the developer's
   ## installation scripts (e.g. configure, etc.)
-  R_PACKAGE_DIR="${lib}/${pkg}"
+  R_PACKAGE_DIR="${2}"
+  R_FULL_PKG="${3}"
   R_LIBRARY_DIR="${lib}"
   R_PACKAGE_NAME="${pkg}"
   export R_LIBRARY_DIR
   export R_PACKAGE_DIR
   export R_PACKAGE_NAME
+
+  message "Installing *source* package '${R_FULL_PKG}' ..."
+
 
   if ${use_configure} && test -x ./configure ; then
     eval ${configure_vars} ./configure ${configure_args}
@@ -290,7 +306,7 @@ do_install_source () {
   if test -d src; then
     message "libs"
     if ${debug}; then set -x; fi
-    mkdir -p "${lib}/${pkg}/libs"
+    mkdir -p "${R_PACKAGE_DIR}/libs"
     if test -f src/Makefile; then
       cd src;
       makefiles="-f \"${R_HOME}\"/share/make/shlib.mk -f Makefile"
@@ -298,7 +314,7 @@ do_install_source () {
 	makefiles="-f Makevars ${makefiles}"
       fi
       eval ${MAKE} ${makefiles} \
-	&& cp *@SHLIB_EXT@ "${lib}/${pkg}/libs" \
+	&& cp *@SHLIB_EXT@ "${R_PACKAGE_DIR}/libs" \
         || error=true; \
       if ${clean}; then
 	${MAKE} clean
@@ -309,7 +325,7 @@ do_install_source () {
       srcs=`ls *.[cfC] *.cc *.cpp 2>/dev/null`
       if test -n "${srcs}"; then
 	sh "${R_HOME}/bin/SHLIB" -o "${pkg}@SHLIB_EXT@" ${srcs} \
-          && cp *@SHLIB_EXT@ "${lib}/${pkg}/libs" \
+          && cp *@SHLIB_EXT@ "${R_PACKAGE_DIR}/libs" \
 	  || error=true; \
 	if ${clean}; then
 	  rm -rf .libs _libs
@@ -331,23 +347,23 @@ do_install_source () {
     message "R"
     Rfiles=`LC_COLLATE=C ls R/*.[RSqrs] R/${R_OSTYPE}/*.[RSqrs] 2>/dev/null`
     if test -n "${Rfiles}"; then
-      mkdir -p "${lib}/${pkg}/R"
-	rm -f "${lib}/${pkg}/R/"*
-	echo ".packageName <- \"${pkg}\"" > "${lib}/${pkg}/R/${pkg}"
-      cat ${Rfiles} >> "${lib}/${pkg}/R/${pkg}"
+      mkdir -p "${R_PACKAGE_DIR}/R"
+	rm -f "${R_PACKAGE_DIR}/R/"*
+	echo ".packageName <- \"${R_FULL_PKG}\"" > "${R_PACKAGE_DIR}/R/${pkg}"
+      cat ${Rfiles} >> "${R_PACKAGE_DIR}/R/${pkg}"
     fi
   fi
 
   if test -d data; then
     message "data"
-    mkdir -p "${lib}/${pkg}/data"
-    rm -f "${lib}/${pkg}/data/"*
-    cp data/* "${lib}/${pkg}/data" 2>/dev/null
-    chmod 644 "${lib}/${pkg}/data/"*
+    mkdir -p "${R_PACKAGE_DIR}/data"
+    rm -f "${R_PACKAGE_DIR}/data/"*
+    cp data/* "${R_PACKAGE_DIR}/data" 2>/dev/null
+    chmod 644 "${R_PACKAGE_DIR}/data/"*
     if test -n "${use_zip_data}" \
         -a -n "${R_UNZIPCMD}" \
         -a -n "${R_ZIPCMD}"; then
-      (cd "${lib}/${pkg}/data";
+      (cd "${R_PACKAGE_DIR}/data";
         find . -type f -print > filelist
         ${R_ZIPCMD} -m Rdata * -x filelist 00Index)
     fi
@@ -355,18 +371,18 @@ do_install_source () {
 
   if test -d demo; then
     message "demo"
-    mkdir -p "${lib}/${pkg}/demo"
-    rm -f "${lib}/${pkg}/demo/"*
-    cp demo/* "${lib}/${pkg}/demo" 2>/dev/null
-    chmod 644 "${lib}/${pkg}/demo/"*
+    mkdir -p "${R_PACKAGE_DIR}/demo"
+    rm -f "${R_PACKAGE_DIR}/demo/"*
+    cp demo/* "${R_PACKAGE_DIR}/demo" 2>/dev/null
+    chmod 644 "${R_PACKAGE_DIR}/demo/"*
   fi
 
   if test -d exec; then
     message "exec"
-    mkdir -p "${lib}/${pkg}/exec"
-    rm -f "${lib}/${pkg}/exec/"*
-    cp exec/* "${lib}/${pkg}/exec" 2>/dev/null
-    chmod 755 "${lib}/${pkg}/exec/"*
+    mkdir -p "${R_PACKAGE_DIR}/exec"
+    rm -f "${R_PACKAGE_DIR}/exec/"*
+    cp exec/* "${R_PACKAGE_DIR}/exec" 2>/dev/null
+    chmod 755 "${R_PACKAGE_DIR}/exec/"*
   fi
 
   if test -d inst; then
@@ -376,12 +392,12 @@ do_install_source () {
     ## should really exclude the CVS subdirs.  (In fact, we should also
     ## exclude everything in @file{.Rbuildignore}, but that's another
     ## story ...)
-    cp -r inst/* "${lib}/${pkg}"
+    cp -r inst/* "${R_PACKAGE_DIR}"
   fi
 
   ## Install the NAMESPACE file if present
   if test -f NAMESPACE; then
-    cp NAMESPACE "${lib}/${pkg}/NAMESPACE"
+    cp NAMESPACE "${R_PACKAGE_DIR}/NAMESPACE"
   fi
 
   case ${save} in
@@ -414,26 +430,26 @@ do_install_source () {
     (echo "options(save.image.defaults=${save_image_defaults})"; \
       if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
       echo "invisible(.libPaths(c(\"${lib}\", .libPaths())))"; \
-      cat "${lib}/${pkg}/R/${pkg}") | \
+      cat "${R_PACKAGE_DIR}/R/${pkg}") | \
 	  ${R_EXE} --slave --save ${save_args}
     ## </NOTE>
     if test ${?} -ne 0; then
       echo "ERROR: execution of package source for '${pkg}' failed"
 	exit 1
     fi
-    mv .RData "${lib}/${pkg}/R/all.rda"
-    mv "${lib}/${pkg}/R/${pkg}" "${lib}/${pkg}/R/${pkg}.R"
-    cat "${R_HOME}/share/R/firstlib.R" > "${lib}/${pkg}/R/${pkg}"
+    mv .RData "${R_PACKAGE_DIR}/R/all.rda"
+    mv "${R_PACKAGE_DIR}/R/${pkg}" "${R_PACKAGE_DIR}/R/${pkg}.R"
+    cat "${R_HOME}/share/R/firstlib.R" > "${R_PACKAGE_DIR}/R/${pkg}"
     ## If install.R is non-empty, arrange to evaluate the R code it
     ## contains after the package source (maybe for some kind of
     ## cleanup).
     if test -s install.R; then
-      cat install.R >> "${lib}/${pkg}/R/${pkg}"
+      cat install.R >> "${R_PACKAGE_DIR}/R/${pkg}"
     fi
   fi
 
   for f in COPYING; do
-    if test -f "${f}"; then cp "${f}" "${lib}/${pkg}"; fi
+    if test -f "${f}"; then cp "${f}" "${R_PACKAGE_DIR}"; fi
   done
   ## Copy DESCRIPTION file, stamp with build information, and remove
   ## blank lines.  (Need to add an empty line to deal with missing
@@ -445,7 +461,7 @@ do_install_source () {
     ## What if there is no DESCRIPTION file?
     ## Shouldn't we fail right away then?
     ## </FIXME>
-    echo ".installPackageDescription(\".\", \"${lib}/${pkg}\")" | \
+    echo ".installPackageDescription(\".\", \"${R_PACKAGE_DIR}\")" | \
       R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null 2>&1
   fi
 
@@ -454,11 +470,11 @@ do_install_source () {
     ## Install man sources ...
     Rdfiles=`ls man/*.[Rr]d man/${R_OSTYPE}/*.[Rr]d 2>/dev/null`
     if test -n "${Rdfiles}"; then
-      mkdir -p "${lib}/${pkg}/man"
-      rm -f "${lib}/${pkg}/man/"*
+      mkdir -p "${R_PACKAGE_DIR}/man"
+      rm -f "${R_PACKAGE_DIR}/man/"*
       for f in ${Rdfiles}; do cat "${f}"; echo '\eof'; done \
-        > "${lib}/${pkg}/man/${pkg}.Rd"
-      chmod 644 "${lib}/${pkg}/man/${pkg}.Rd"
+        > "${R_PACKAGE_DIR}/man/${pkg}.Rd"
+      chmod 644 "${R_PACKAGE_DIR}/man/${pkg}.Rd"
     fi
     ## Maybe build preformatted help pages ...
     if ${build_help}; then
@@ -466,10 +482,10 @@ do_install_source () {
 	echo "${NO_PERL5_MSG}"
       else
 	if ${debug}; then
-	  echo "DEBUG: build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}"
+	  echo "DEBUG: build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib} ${R_LIB_DIR}/${R_FULL_PKG}"
 	fi
 	${R_CMD} perl "${R_HOME}/share/perl/build-help.pl" \
-	  ${build_help_opts} "../${pkg}" "${lib}"
+	  ${build_help_opts} "../${pkg}" "${lib}" "${R_LIB_DIR}/${R_FULL_PKG}"
 	if test ${?} -ne 0; then
 	  echo "ERROR: building help failed for package '${pkg}'"
 	  exit 6
@@ -481,7 +497,7 @@ do_install_source () {
       if test -n "${use_zip_help}" \
 	  -a -n "${R_UNZIPCMD}" \
 	  -a -n "${R_ZIPCMD}"; then
-	(cd "${lib}/${pkg}"
+	(cd "${R_PACKAGE_DIR}"
 	  if test -d R-ex; then
 	    (cd R-ex; ${R_ZIPCMD} -m Rex *.R)
 	  fi
@@ -498,7 +514,7 @@ do_install_source () {
     echo "No man pages found in package '${pkg}'"
   fi
 
-  echo ".installPackageIndices(\".\", \"${lib}/${pkg}\")" | \
+  echo ".installPackageIndices(\".\", \"${R_PACKAGE_DIR}\")" | \
     R_DEFAULT_PACKAGES=tools ${R_EXE} --vanilla >/dev/null 2>&1
 
   if ${clean}; then
@@ -517,32 +533,51 @@ do_install () {
   cd "${1}"
   pkg=`basename "${1}"`
 
-  depends=`get_dcf_field Depends DESCRIPTION`
-  depends=`echo "${depends}" | grep 'R *('`
-  if test "${depends}"; then
-    depends=`echo "${depends}" | sed 's/.*R *(\([^)]*\)).*/\1/;s/=/= /'`
-    dep_operator=`set - ${depends}; echo ${1}`
-    dep_version=`set - ${depends}; echo ${2}`
-    ## Currently, only operators '<=' and '>=' are supported.  Hence we
-    ## check this, and also whether we found a version string.
-    if (test "${dep_operator}" = "<=" \
-	|| test "${dep_operator}" = ">=") \
-	&& test -n "${dep_version}"; then
-      dep_ok=`expr ${R_VERSION} ${dep_operator} ${dep_version} `
-      if test ${dep_ok} -eq 0; then
-	echo "ERROR: This R is version ${R_VERSION}"
-	echo "       package '${pkg}' depends on R ${dep_version}"
-	exit 1;
+  ## Set R_PACKAGE_DIR here at the top level.  If a version
+  ## is being specified, tack that on.  Also changed all
+  ## occurances of ${lib}/$[pkg} with R_PACKAGE_DIR JG
+  if ${package_versions}; then
+    ## Get package version
+    version=`get_dcf_field Version DESCRIPTION`
+    R_FULL_PKG="${lib}/${pkg}_${version}"
+    R_PACKAGE_DIR="${lib}/${pkg}_${version}"
+  else
+      R_FULL_PKG="${lib}/${pkg}"
+      R_PACKAGE_DIR="${R_FULL_PKG}"
+  fi
+  export R_PACKAGE_DIR
+  export R_FULL_PKG
+
+  ## Unrelated to toher changes, put in the ability to force a package
+  ## to be installed even if the R version does not match up. JG
+  if ${check_R_version}; then
+    depends=`get_dcf_field Depends DESCRIPTION`
+    depends=`echo "${depends}" | grep 'R *('`
+    if test "${depends}"; then
+      depends=`echo "${depends}" | sed 's/.*R *(\([^)]*\)).*/\1/;s/=/= /'`
+      dep_operator=`set - ${depends}; echo ${1}`
+      dep_version=`set - ${depends}; echo ${2}`
+      ## Currently, only operators '<=' and '>=' are supported.  Hence we
+      ## check this, and also whether we found a version string.
+	if (test "${dep_operator}" = "<=" \
+	  || test "${dep_operator}" = ">=") \
+	  && test -n "${dep_version}"; then
+	dep_ok=`expr ${R_VERSION} ${dep_operator} ${dep_version} `
+	if test ${dep_ok} -eq 0; then
+	  echo "ERROR: This R is version ${R_VERSION}"
+	  echo "       package '${pkg}' depends on R ${dep_version}"
+	  exit 1;
+	fi
+      else
+	echo "WARNING: malformed 'Depends' field in 'DESCRIPTION'"
       fi
-    else
-      echo "WARNING: malformed 'Depends' field in 'DESCRIPTION'"
     fi
   fi
 
-  mkdir -p "${lib}/${pkg}" || exit 2
+  mkdir -p "${R_PACKAGE_DIR}" || exit 2
 
   ## Make sure we do not attempt installing to srcdir.
-  if test "`cd \"${lib}/${pkg}\" && ${GETWD}`" = "`${GETWD}`"; then
+  if test "`cd \"${R_PACKAGE_DIR}\" && ${GETWD}`" = "`${GETWD}`"; then
     echo "ERROR: cannot install to srcdir"
     exit 3
   fi  
@@ -570,13 +605,13 @@ do_install () {
 
   if ${is_source_package}; then
     ## This is a source package ... hopefully.
-    do_install_source "${pkg}"
+    do_install_source "${pkg}" "${R_PACKAGE_DIR}" "${R_FULL_PKG}"
   else  
     ## This is a binary package ... hopefully.
-    do_install_binary "${pkg}"
+    do_install_binary "${pkg}" "${R_PACKAGE_DIR}" "${R_FULL_PKG}"
   fi
 
-  chmod -R a+r "${lib}/${pkg}"
+  chmod -R a+r "${R_PACKAGE_DIR}"
 
   ## <FIXME>
   ## This is really something we should do once at the end, and not for
