Add sanity check for `Depends' info.
git-svn-id: https://svn.r-project.org/R/trunk@14053 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.62 $'
+revision='$Revision: 1.63 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -202,11 +202,19 @@ do_install () {
     depends=`echo ${depends} | sed 's/.*R *(\([^)]*\)).*/\1/;s/=/= /'`
     dep_operator=`set - ${depends}; echo ${1}`
     dep_version=`set - ${depends}; echo ${2}`
-    dep_ok=`expr ${R_VERSION} ${dep_operator} ${dep_version} `
-    if test ${dep_ok} -eq 0; then
-      echo "ERROR: This R is version ${R_VERSION}"
-      echo "       package \`${pkg}' depends on R ${dep_version}"
-      exit 1;
+    ## Currently, only operators `<=' and `>=' are supported.  Hence we
+    ## check this, and also whether we found a version string.
+    if (test "${dep_operator}" = "<=" \
+	|| test "${dep_operator}" = ">=") \
+	&& test -n "${dep_version}"; then
+      dep_ok=`expr ${R_VERSION} ${dep_operator} ${dep_version} `
+      if test ${dep_ok} -eq 0; then
+	echo "ERROR: This R is version ${R_VERSION}"
+	echo "       package \`${pkg}' depends on R ${dep_version}"
+	exit 1;
+      fi
+    else
+      echo "WARNING: malformed \`Depends' field in \`DESCRIPTION'"
     fi
   fi
 
