fixup update breakage
git-svn-id: https://svn.r-project.org/R/trunk@6143 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -71,10 +71,6 @@ while test -n "${1}"; do
     -l|--library)
       lib=${2}; shift ;;
     *)
-<<<<<<< INSTALL.in
-      if test -d "${1}"; then
-	PKGS="${PKGS} \"`cd "${1}"; pwd`\""
-=======
       if test -f "${1}"; then
         mkdir -p ${TMPDIR}
 	PKGNAME=`basename "${1}"`
@@ -88,6 +84,162 @@ while test -n "${1}"; do
 	fi    
       elif test -d "${1}"; then
 	PKGS="${PKGS} \"`cd "${1}"; pwd`\""
+      else
+	echo "WARNING: package \`"${1}"' does not exist"
+      fi
+      ;;
+  esac
+  shift
+done
+
+if test -z "${PKGS}"; then
+  echo "${USAGE_MSG}"
+  exit 1
+fi
+
+if test -d ${lib} -a -w ${lib} || mkdir ${lib} 2> /dev/null; then
+  lib=`cd ${lib}; pwd`
+else
+  echo "ERROR:  cannot write to or create directory \`${lib}'"
+  exit 2
+fi
+
+if ${BUILD_TEXT}; then
+  BUILD_HELP_OPTS="${BUILD_HELP_OPTS} --nroff"
+fi
+if ${BUILD_HTML}; then
+  BUILD_HELP_OPTS="${BUILD_HELP_OPTS} --html"
+fi
+if ${BUILD_LATEX}; then
+  BUILD_HELP_OPTS="${BUILD_HELP_OPTS} --latex"
+fi
+if ${BUILD_EXAMPLE}; then
+  BUILD_HELP_OPTS="${BUILD_HELP_OPTS} --example"
+fi
+if test -z "${BUILD_HELP_OPTS}"; then
+  BUILD_HELP=false
+elif ${DEBUG}; then
+  BUILD_HELP_OPTS="--debug ${BUILD_HELP_OPTS}"
+fi
+
+do_install () {
+  cd "${1}"
+  pkg=`basename "${1}"`
+
+  mkdir -p ${lib}/${pkg} || exit 3
+  echo "Installing package \`${pkg}' ..."
+
+  if test -x ./configure ; then
+    ./configure
+  fi
+
+  if test -d src; then
+    echo " libs"
+    if ${DEBUG}; then set -x; fi
+    mkdir -p ${lib}/${pkg}/libs
+    if test -f src/Makefile; then
+      (cd src;
+	${MAKE} -f ${R_HOME}/etc/Makeconf -f Makefile \
+	  && cp *.@SHLIBEXT@ ${lib}/${pkg}/libs \
+	  || ERROR=true; \
+	if ${CLEAN}; then ${MAKE} clean; fi)
+    else
+      (cd src;
+	sh ${R_HOME}/bin/SHLIB ${SHLIB_OPTS} \
+	   -o ${lib}/${pkg}/libs/${pkg}.@SHLIBEXT@ *.[cf] \
+	  || ERROR=true; \
+	if ${CLEAN}; then rm -f *.o; fi)
+    fi
+    if ${ERROR}; then
+      echo "ERROR: Compilation failed for package \`${pkg}'"
+      exit 4
+    fi
+    if ${DEBUG}; then set +x; fi
+  fi
+
+  if test -d R; then dir=R; elif test -d funs; then dir=funs; fi
+  if test "${dir}"; then
+    echo " ${dir}"
+    mkdir -p ${lib}/${pkg}/R
+    cat `ls ${dir}/*.[RSqrs]` > ${lib}/${pkg}/R/${pkg}
+  fi
+  dir=
+
+  if test -d data; then
+    echo " data"
+    mkdir -p ${lib}/${pkg}/data
+    cp data/* ${lib}/${pkg}/data
+    chmod 644 ${lib}/${pkg}/data/*
+  fi
+
+  if test -d exec; then
+    echo " exec"
+    mkdir -p ${lib}/${pkg}/exec
+    cp exec/* ${lib}/${pkg}/exec
+    chmod 755 ${lib}/${pkg}/exec/*
+  fi
+
+  if test -d inst; then
+    echo " inst"
+    cp -r inst/* ${lib}/${pkg}
+  fi
+
+  if test -f INDEX; then
+    cp INDEX ${lib}/${pkg}
+  fi
+  if test -f TITLE; then
+    cp TITLE ${lib}/${pkg}
+  fi
+  if test -f DESCRIPTION; then
+    cp DESCRIPTION ${lib}/${pkg}
+  fi
+  (cd ${lib}; cat */TITLE > LibIndex 2> /dev/null)
+
+  if test -d man; then
+    echo " help"
+    if ${BUILD_HELP}; then
+      if ${NO_PERL5}; then
+	echo "${NO_PERL5_MSG}"
+      else
+	if ${DEBUG}; then
+	  echo "  ${R_HOME}/bin/build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}"
+	fi
+	${R_HOME}/bin/build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}
+	${R_HOME}/bin/Rd2contents ../${pkg} > ${lib}/${pkg}/CONTENTS
+	if test ${lib} = ${R_HOME}/library; then 
+	  ${R_HOME}/bin/build-help --htmllists
+	  cat ${R_HOME}/library/*/CONTENTS \
+	    > ${R_HOME}/doc/html/search/index.txt
+	fi	
+      fi
+      if test -n "${USE_ZIP}" -a -n "${R_UNZIPCMD}" -a -n "${R_ZIPCMD}"; then
+	cd ${lib}/${pkg}
+	if test -d R-ex; then
+	  (cd R-ex; ${R_ZIPCMD} -m Rhelp *.R)
+	fi
+	## NOT YET:
+	## if test -d latex; then
+	##   (cd latex; ${R_ZIPCMD} -m Rhelp *.tex)
+	## fi
+	if test -d help; then
+	  (cd help; ${R_ZIPCMD} -m Rhelp * -x 00Titles AnIndex);
+	fi
+      fi
+    fi
+  else
+    echo "  No man pages found in package \`${pkg}'"
+  fi
+
+  if ${CLEAN}; then
+    if test -x ./cleanup ; then
+      ./cleanup
+    fi
+  fi
+
+  chmod -R a+r ${lib}/${pkg}
+
+  echo " DONE (${pkg})"
+  echo
 }
 
 eval "for pkg in ${PKGS}; do do_install \"\${pkg}\"; done"
