ported r33596:34862 from main
git-svn-id: https://svn.r-project.org/R/branches/R-noNULLenv@34864 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -91,14 +91,14 @@ warning () { echo "WARNING: $*" >&2 ; }
 error ()   { echo "ERROR: $*" >&2 ; }
 
 startdir=`${GETWD}`
-tmpdir="${TMPDIR-/tmp}/R.INSTALL.$$"
-if (test -d "${tmpdir}" && test -w "${tmpdir}") || \
-    ${MKDIR_P} "${tmpdir}" 2> /dev/null; then
-  tmpdir=`cd "${tmpdir}" && ${GETWD}`
-else
-  error "cannot write to or create temporary directory '${tmpdir}'"
-  exit 1
-fi
+: ${TMPDIR=/tmp}
+{ tmpdir=`(mktemp -d -q "${TMPDIR}/R.INSTALL.XXXXXX") 2>/dev/null` \
+    && test -n "${tmpdir}" && test -d "${tmpdir}" ; } ||
+  { test -n "${RANDOM}" && tmp=${TMPDIR}/R.INSTALL$$-${RANDOM} \
+      && (${MKDIR_P} "${tmpdir}") ; } ||
+  { tmpdir=${TMPDIR}/R.INSTALL.$$ && (${MKDIR_P} "${tmpdir}") ; } ||
+  (error "cannot create temporary directory" && exit 1)
+tmpdir=`cd "${tmpdir}" && ${GETWD}`
 
 : ${R_OSTYPE=unix}
 ## <NOTE>
@@ -116,7 +116,7 @@ message () { echo "${stars} $*"; }
 stars="*"
 ## </NOTE>
 
-. "${R_HOME}/share/sh/dcf.sh"	# get_dcf_field()
+. "${R_SHARE_DIR}/sh/dcf.sh"	# get_dcf_field()
 
 tilde_expand () {
     h=`echo "${HOME}" | sed 's,/,\\\/,g'`
@@ -279,7 +279,7 @@ while test -n "${1}"; do
 	## Otherwise, the build date for an older version may be newer
 	## than the modification date for the new sources as recorded in
 	## the tarball ...
-	gzip -dc "${1}" | (cd "${tmpdir}" && ${TAR} -mxf -)
+	${R_GZIPCMD} -dc "${1}" | (cd "${tmpdir}" && ${TAR} -mxf -)
 	## If we have a binary bundle distribution, the DESCRIPTION file
 	## is at top level.
 	if test -f "${tmpdir}/DESCRIPTION"; then
@@ -460,7 +460,7 @@ do_install_source () {
   if test "$Type" = "Translation" ; then
     message "Installing *Translation* package '${pkg_name}' ..."
     if test -d "share"; then
-      cp -r ./share ${R_HOME}
+      cp -r ./share/* ${R_SHARE_DIR}
     fi
     if test -d "library"; then
       cp -r ./library ${R_HOME}
@@ -536,7 +536,7 @@ do_install_source () {
     ${MKDIR_P} "${R_PACKAGE_DIR}/libs"
     if test -f src/Makefile; then
       cd src;
-      makefiles="-f \"${R_HOME}\"/share/make/shlib.mk -f Makefile"
+      makefiles="-f \"${R_SHARE_DIR}\"/make/shlib.mk -f Makefile"
       if test -r "${HOME}/.R/Makevars-${R_PLATFORM}"; then
 	  makefiles="${makefiles} -f \"${HOME}/.R/Makevars-${R_PLATFORM}\""
       elif test -r "${HOME}/.R/Makevars"; then
@@ -589,7 +589,7 @@ do_install_source () {
     fi
     if ${fake}; then
       if test -f NAMESPACE; then
-        (echo; echo ".onLoad <- function(list, pkg) NULL") >> \
+        (echo; echo ".onLoad <- .onAttach <- function(lib, pkg) NULL") >> \
 	  "${R_PACKAGE_DIR}/R/${R_PACKAGE_NAME}"
 	sed -e '/useDynLib/d' NAMESPACE > "${R_PACKAGE_DIR}/NAMESPACE"
       else
@@ -713,7 +713,7 @@ do_install_source () {
     ## we used to install the dumped code but this seems a waste of space
     rm "${code_file}"
     # mv "${code_file}" "${R_PACKAGE_DIR}/R/${pkg_name}.R"
-    cat "${R_HOME}/share/R/${loader_file}" > "${code_file}"
+    cat "${R_SHARE_DIR}/R/${loader_file}" > "${code_file}"
     ## If install.R is non-empty, arrange to evaluate the R code it
     ## contains after the package loader.
     if test -s install.R; then
@@ -744,7 +744,7 @@ do_install_source () {
   if ${thislazy}; then
     message "preparing package for lazy loading"
     (if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
-    echo "tools:::makeLazyLoading(\"${R_PACKAGE_NAME}\", \"${lib}\")") | \
+    echo "invisible(.libPaths(c(\"${lib}\", .libPaths()))); tools:::makeLazyLoading(\"${R_PACKAGE_NAME}\", \"${lib}\")") | \
       R_DEFAULT_PACKAGES= LC_ALL=C "${R_EXE}" --vanilla --slave
     if test ${?} -ne 0; then
       error "lazy loading failed for package '${pkg_name}'"
@@ -780,7 +780,7 @@ do_install_source () {
 	if ${debug}; then
 	  echo "DEBUG: build-help ${build_help_opts} ${pkg_dir} ${lib} ${R_PACKAGE_DIR} ${pkg_name}"
 	fi
-	"${R_CMD}" perl "${R_HOME}/share/perl/build-help.pl" \
+	"${R_CMD}" perl "${R_SHARE_DIR}/perl/build-help.pl" \
 	  ${build_help_opts} \
 	  "${pkg_dir}" "${lib}" "${R_PACKAGE_DIR}" "${pkg_name}"
 	if test ${?} -ne 0; then
@@ -859,7 +859,7 @@ do_install_source () {
     filename="${R_PACKAGE_NAME}_${version}_R_${R_PLATFORM}.tar"
     filepath="${startdir}/$filename"
     ${TAR} -chf "$filepath" -C "${R_LIBRARY_DIR}" ${R_PACKAGE_NAME}
-    gzip -9f "$filepath"
+    ${R_GZIPCMD} -9f "$filepath"
     echo "packaged installation of '${R_PACKAGE_NAME}' as ${filename}.gz"
   fi
 
@@ -989,13 +989,14 @@ do_cleanup () {
   if test "${is_first_package}" = no; then
     ## Only need to do this in case we successfully installed at least
     ## *one* package ... well not so sure for bundles.
-    cp "${R_HOME}/doc/html/R.css" "${lib}"
+    cp "${R_DOC_DIR}/html/R.css" "${lib}"
     chmod 644 "${lib}/R.css"
     if test "${lib}" = "`cd \"${R_HOME}/library\" && ${GETWD}`"; then
       cat "${R_HOME}"/library/*/CONTENTS \
-        > "${R_HOME}"/doc/html/search/index.txt
+        > "${R_DOC_DIR}"/html/search/index.txt
       if ${build_help} && test "${NO_PERL5}" = "false"; then
-        "${R_CMD}" perl "${R_HOME}/share/perl/build-help.pl" --htmllists
+        echo "tools:::unix.packages.html(.Library, docdir=\"${R_DOC_DIR}\")" | \
+          R_DEFAULT_PACKAGES=NULL LC_COLLATE=C "${R_EXE}" --vanilla >/dev/null
       fi
     fi
   fi
