make use of R_PDFLATEXCMD R CMD Rd2dvi gives explicit error message if R_{PDF}LATEXCMD is false
git-svn-id: https://svn.r-project.org/R/branches/R-2-8-branch@46875 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/Rd2dvi b/src/scripts/Rd2dvi
--- a/src/scripts/Rd2dvi
+++ b/src/scripts/Rd2dvi
@@ -102,7 +102,11 @@ while test -n "${1}"; do
 	fi
       fi
       R_RD4DVI=${R_RD4PDF-"times,hyper"}
-      R_LATEXCMD=${PDFLATEX-pdflatex}
+      if test "${R_PDFLATEXCMD}" = false; then
+	echo "ERROR: 'pdflatex' needed but missing on your system."
+	exit 1
+      fi
+      R_LATEXCMD=${R_PDFLATEXCMD}
       ;;
     --title=*)
       title=`echo "${1}" | ${SED} -e 's/[^=]*=//'` ;;
@@ -131,6 +135,12 @@ while test -n "${1}"; do
   esac
   shift
 done
+
+## We already checked in the case of --pdf
+if test "${R_LATEXCMD}" = false; then
+  echo "ERROR: 'latex' needed but missing on your system."
+  exit 1
+fi
 
 if ${debug}; then set -x; fi
 
