port patch for spaces & Rd2dvi from R-2-11-branch Can't have \ in libdir in R CMD check, it seems
git-svn-id: https://svn.r-project.org/R/trunk@52232 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/Rd2dvi b/src/scripts/Rd2dvi
--- a/src/scripts/Rd2dvi
+++ b/src/scripts/Rd2dvi
@@ -150,8 +150,8 @@ if ${debug}; then set -x; fi
 
 do_cleanup () {
   if ${clean}; then
-    cd ${start_dir}
-    rm -rf ${build_dir}
+    cd "${start_dir}"
+    rm -rf "${build_dir}"
   else
     echo "You may want to clean up by 'rm -rf ${build_dir}'"
   fi
@@ -198,10 +198,10 @@ if test -f ${output}; then
   echo "file '${output}' exists; please remove first"
   exit 1
 fi
-if test -d ${build_dir}; then
-  rm -rf ${build_dir} || echo "cannot write to build dir" && exit 2
+if test -d "${build_dir}"; then
+  rm -rf "${build_dir}" || echo "cannot write to build dir" && exit 2
 fi
-mkdir ${build_dir}
+mkdir "${build_dir}"
 
 echo "tools:::.Rd2dvi(\"${1}\",  \"${build_dir}/Rd2.tex\", \
 \"$title\", \"$batch\", \"$description\", \"$only_meta\",\
@@ -209,7 +209,7 @@ echo "tools:::.Rd2dvi(\"${1}\",  \"${build_dir}/Rd2.tex\", \
   | LC_ALL=C ${R_HOME}/bin/R --slave --vanilla || exit 11
 
 echo "Creating ${out_ext} output from LaTeX ..."
-cd ${build_dir}
+cd "${build_dir}"
 
 status=0
 echo "tools::texi2dvi('Rd2.tex', pdf=(\"${out_ext}\" == \"pdf\"), \
@@ -221,9 +221,9 @@ if test $status -gt 0; then
   exit 1
 fi
 
-cd ${start_dir}
+cd "${start_dir}"
 echo "Saving output to '${output}' ..."
-cp ${build_dir}/Rd2.${out_ext} ${output}
+cp "${build_dir}/Rd2.${out_ext}" ${output}
 echo "Done"
 
 do_cleanup
