improve error handing
git-svn-id: https://svn.r-project.org/R/trunk@52047 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/Rd2dvi b/src/scripts/Rd2dvi
--- a/src/scripts/Rd2dvi
+++ b/src/scripts/Rd2dvi
@@ -205,9 +205,15 @@ echo "tools:::.Rd2dvi(\"${1}\",  \"${build_dir}/Rd2.tex\", \
 echo "Creating ${out_ext} output from LaTeX ..."
 cd ${build_dir}
 
+status=0
 echo "tools::texi2dvi('Rd2.tex', pdf=(\"${out_ext}\" == \"pdf\"), \
     quiet=FALSE, index=(\"${index}\" != \"false\"))" | \
-   LC_ALL=C ${R_HOME}/bin/R --slave --vanilla || do_cleanup && exit 1
+   LC_ALL=C ${R_HOME}/bin/R --slave --vanilla || status=1
+if test $status -gt 0; then
+  echo "Error in running tools::texi2dvi"
+  do_cleanup
+  exit 1
+fi
 
 cd ${start_dir}
 echo "Saving output to '${output}' ..."
