Ensure GNU-style option naming and handling.
git-svn-id: https://svn.r-project.org/R/trunk@7367 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/src/scripts/Rd2dvi b/src/scripts/Rd2dvi
--- a/src/scripts/Rd2dvi
+++ b/src/scripts/Rd2dvi
@@ -6,144 +6,156 @@
 #  R CMD Rd2dvi `grep -l "\\keyword{distr" \
 #                  /path/to/Rsrc/src/library/base/man/*.Rd | sort | uniq`
 
-REVISION='$Revision: 1.15 $'
-VERSION=`set - ${REVISION}; echo ${2}`
-USAGE_MSG="Usage: R CMD Rd2dvi [options] files"
+revision='$Revision: 1.16 $'
+version=`set - ${revision}; echo ${2}`
+version="Rd2dvi ${version}" 
 
-START_DIR=`pwd`
+usage="Usage: R CMD Rd2dvi [options] files
 
-CLEAN=true
-DEBUG=false
-USE_XDVI=true
-DVI_EXT="dvi"
-OUTPUT=""
+Generate DVI (or PDF) output from the Rd sources specified by files, by
+either giving the paths to the files, or the path to a directory with
+the sources of a package.
+
+Options:
+  --debug		turn on shell debugging (set -x)
+  -h, --help		print short help message and exit
+  --no-clean		do not remove created temporary files
+  --no-preview		do not preview generated output file
+  --output=FILE		write output to FILE
+  --pdf			generate PDF output
+  --title=NAME		use NAME as the title of the document
+  -v, --version		print version info and exit
+  -V, --verbose		report on what is done
+
+Report bugs to <R-bugs@lists.r-project.org>."
+
+start_dir=`pwd`
+
+clean=true
+debug=false
+dvi_ext="dvi"
+output=""
+preview=xdvi
+verbose=false
+
 TEXINPUTS=.:${R_HOME}/doc/manual:${TEXINPUTS}
 
 file_sed='s/[_$]/\\\\&/g'
 
 while test -n "${1}"; do
   case ${1} in
-    -h|--help|-\?)
-      echo "${USAGE_MSG}"; exit 0 ;;
-    -V|--version)
-      echo "${VERSION}"; exit 0 ;;
-    --clean=[nN]*)
-      CLEAN=false ;;
-    --clean=[yY]*)
-      CLEAN=true ;;
-    --debug=[nN]*)
-      DEBUG=false ;;
-    --debug=[yY]*)
-      DEBUG=true ;;
-    --use-xdvi=[nN]*)
-      USE_XDVI=false ;;
-    --use-xdvi=[yY]*)
-      USE_XDVI=true ;;
+    -h|--help)
+      echo "${usage}"; exit 0 ;;
+    -v|--version)
+      echo "${version}"; exit 0 ;;
+    --debug)
+      debug=true ;;
+    --no-clean)
+      clean=false ;;
+    --no-preview)
+      preview=false ;;
     --pdf)
-      DVI_EXT="pdf";
-      USE_XDVI=false;
+      dvi_ext="pdf";
+      preview=false;
       R_RD4DVI=${R_RD4PDF:-"ae,hyper"};
       R_LATEXCMD=${PDFLATEX:-pdflatex};;
     --title=*)
-      TITLE=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
+      title=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
     --output=*)
-      OUTPUT=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
+      output=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
+    -V|--verbose)
+      verbose=echo ;;
     --|*)
       break ;;
   esac
   shift
 done
 
-if test -z ${OUTPUT}; then
-  OUTPUT=Rd2.${DVI_EXT}
+if test -z ${output}; then
+  output=Rd2.${dvi_ext}
 fi
 
-TOC="\\Rdcontents{\\R{} objects documented:}"
+if ${debug}; then set -x; fi
+
+toc="\\Rdcontents{\\R{} objects documented:}"
 if [ ${#} -eq 1 -a -d ${1} ]; then
   if test -d ${1}/man; then
     dir=${1}/man
   else
     dir=${1}
   fi
-  if ${DEBUG}; then
-    echo "Rd2dvi: \`Rdconv -t latex' ${dir}/ Rd files ..."
-  fi
+  ${verbose} "Rd2dvi: \`Rdconv -t latex' ${dir}/ Rd files ..."
   files=`find ${dir} -name "*.[Rr]d" -print`
   subj="all in \\file{`echo ${dir} | sed ${file_sed}`}"
-  if ${DEBUG}; then  
-    echo "files = ${files}"
-  fi
+  ${verbose} "files = ${files}"
 else
   files="${@}"
   if [ ${#} -gt 1 ]; then
     subj=" etc.";
   else
     subj=
-    TOC=
+    toc=
   fi
   subj="\\file{`echo ${1} | sed ${file_sed}`}${subj}"
-  if ${DEBUG}; then
-    echo "Rd2dvi: Collecting files and \`Rdconv -t latex'ing them ..."
-  fi
+  ${verbose} "Rd2dvi: Collecting files and \`Rdconv -t latex'ing them ..."
 fi
 
-if ${DEBUG}; then
-  echo ""; echo "subj:"; echo "${subj}"; echo ""
-fi
+${verbose} ""
+${verbose} "subj: ${subj}"
+${verbose} ""
 
-if test -f ${OUTPUT}; then
-  echo "file \`${OUTPUT}' exists; please remove first"
+if test -f ${output}; then
+  echo "file \`${output}' exists; please remove first"
   exit 1
 fi
-BUILD_DIR=.Rd2dvi${$}
-if test -d ${BUILD_DIR}; then
-  rm -rf ${BUILD_DIR} || echo "cannot write to build dir" && exit 2
+build_dir=.Rd2dvi${$}
+if test -d ${build_dir}; then
+  rm -rf ${build_dir} || echo "cannot write to build dir" && exit 2
 fi
-mkdir ${BUILD_DIR}
+mkdir ${build_dir}
 
 sed 's/markright{#1}/markboth{#1}{#1}/' \
-  ${R_HOME}/doc/manual/Rd.sty > ${BUILD_DIR}/Rd2.sty
+  ${R_HOME}/doc/manual/Rd.sty > ${build_dir}/Rd.sty
 
-TITLE=${TITLE:-"\\R{} documentation}} \\par\\bigskip{{\\Large of ${subj}"}
+title=${title:-"\\R{} documentation}} \\par\\bigskip{{\\Large of ${subj}"}
 
-cat > ${BUILD_DIR}/Rd2.tex <<EOF
+cat > ${build_dir}/Rd2.tex <<EOF
 \\documentclass[${R_PAPERSIZE}paper]{book}
-\\usepackage[${R_RD4DVI:-ae}]{Rd2}
+\\usepackage[${R_RD4DVI:-ae}]{Rd}
 \\usepackage{makeidx}
 \\makeindex
 \\begin{document}
 \\chapter*{}
 \\begin{center}
-{\\textbf{\\huge ${TITLE}}}
+{\\textbf{\\huge ${title}}}
 \\par\\medskip{\\large \\today}
 \\end{center}
 ${TOC}
 EOF
 
 for f in ${files}; do
-  if ${DEBUG}; then echo ${f}; fi
-  R CMD Rdconv -t latex ${f} >> ${BUILD_DIR}/Rd2.tex
+  ${verbose} ${f}
+  R CMD Rdconv -t latex ${f} >> ${build_dir}/Rd2.tex
 done
 
-cat >> ${BUILD_DIR}/Rd2.tex <<EOF  
+cat >> ${build_dir}/Rd2.tex <<EOF
 \\printindex
 \\end{document}
 EOF
 
-cd ${BUILD_DIR}
-${R_LATEXCMD} Rd2
-${R_MAKEINDEXCMD} Rd2
-${R_LATEXCMD} Rd2
-cp Rd2.${DVI_EXT} ../${OUTPUT}
-cd ${START_DIR}
-if ${CLEAN}; then
-  rm -rf ${BUILD_DIR}
+cd ${build_dir}
+${R_LATEXCMD:-latex} Rd2
+${R_MAKEINDEXCMD:-makeindex} Rd2
+${R_LATEXCMD:-latex} Rd2
+cp Rd2.${dvi_ext} ../${output}
+cd ${start_dir}
+if ${clean}; then
+  rm -rf ${build_dir}
 else
-  echo "You may want to clean up by \`rm -rf ${BUILD_DIR}'"
+  echo "You may want to clean up by \`rm -rf ${build_dir}'"
 fi
-if ${USE_XDVI}; then
-  xdvi ${OUTPUT}
-fi
+${preview} ${output}
+exit 0
 
 ### Local Variables: ***
 ### mode: sh ***
