new test targets
git-svn-id: https://svn.r-project.org/R/trunk@23625 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -24,21 +24,21 @@ test-src-gct = \
 test-src-strict-1 = \
 	$(test-src-gct) \
 	d-p-q-r-tests.R
-test-src-strict-auto = \
-	isas-tests.R
+test-src-strict-auto =
 test-src-sloppy-1 = \
 	print-tests.R
 test-src-sloppy-auto =
 
 test-src-1 = $(test-src-strict-1) $(test-src-sloppy-1)
 test-src-auto = $(test-src-strict-auto) $(test-src-sloppy-auto) \
-  ${test-src-segfault}
+  ${test-src-isas} ${test-src-segfault}
 test-src-sloppy = $(test-src-sloppy-1) $(test-src-sloppy-auto)
 test-src-strict = $(test-src-strict-1) $(test-src-strict-auto)
 test-src = $(test-src-strict) $(test-src-sloppy)
 
 test-src-demo = demos.R demos2.R
 test-src-internet = internet.R
+test-src-isas = isas-tests.R
 test-src-lapack = lapack.R
 test-src-nafns = nafns.R
 test-src-random = p-r-random-tests.R
@@ -46,14 +46,10 @@ test-src-postscript = ps-tests.R
 test-src-ts = ts-tests.R
 test-src-segfault = no-segfault.R
 
-test-src-reg-1 = \
-	reg-tests-1.R reg-tests-2.R reg-IO.R reg-IO2.R reg-plot.R
+test-src-reg-1 = reg-tests-1.R reg-tests-2.R reg-IO.R reg-IO2.R reg-plot.R
 test-src-reg-auto =
 test-src-reg = $(test-src-reg-1) $(test-src-reg-auto)
 
-all-basic-tests = Examples Specific Reg Demo Segfault
-all-extra-tests = Internet Lapack Nafns Postscript Random \
-  DocArgs FF Methods codoc undoc
 
 DISTFILES = Makefile.in Makefile.win README \
 	$(test-src-strict-1) $(test-src-strict-1:.R=.Rout.save) \
@@ -82,6 +78,7 @@ test-out-gct = $(test-src-gct:.R=.Rout-gct)
 
 test-out-demo = $(test-src-demo:.R=.Rout)
 test-out-internet = $(test-src-internet:.R=.Rout)
+test-out-isas = $(test-src-isas:.R=.Rout)
 test-out-lapack = $(test-src-lapack:.R=.Rout)
 test-out-nafns = $(test-src-nafns:.R=.Rout)
 test-out-postscript = $(test-src-postscript:.R=.Rout)
@@ -94,13 +91,20 @@ test-out-ts = $(test-src-ts:.R=.Rout)
 test-out = $(test-src:.R=.Rout) $(test-out-demo) $(test-out-gct) \
 	$(test-out-internet) $(test-out-lapack) $(test-out-nafns) \
 	$(test-out-random) $(test-out-postscript) $(test-out-reg) \
-	$(test-out-segfault) $(test-out-ts)
+	$(test-out-segfault) $(test-out-ts) $(test-out-isas)
 
 .SUFFIXES:
 .SUFFIXES: .R .Rin .Rout .Rout-gct
 
+all-basic-tests = Examples Specific Reg Internet
+all-devel-tests = IsAs Lapack Nafns Postscript Random Demo Segfault \
+   Standalone Packages
+all-extra-tests = Lapack Nafns Postscript Random \
+  DocArgs FF Methods codoc undoc
+
 all check: Makefile test-all-basics
-fullcheck: check test-Examples-Recommended
+check-devel: check test-all-devel
+check-all: check-devel test-Examples-Recommended
 
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
@@ -177,6 +181,10 @@ test-all-basics: Makefile
 	@for name in $(all-basic-tests); do \
 	  $(MAKE) test-$${name} || exit 1; \
 	done
+test-all-devel: Makefile
+	@for name in $(all-devel-tests); do \
+	  $(MAKE) test-$${name} || exit 1; \
+	done
 test-Examples:
 	@(cd Examples && $(MAKE) $@)
 test-Examples-Recommended:
@@ -190,7 +198,6 @@ test-Specific:
 	@$(MAKE) test-Specific-strict RVAL_IF_DIFF=1
 	@echo "running sloppy specific tests"
 	@$(MAKE) test-Specific-sloppy RVAL_IF_DIFF=0
-	@rm -f data dumpdata.R  F.Rd c0.Rd df0.Rd l0.Rd m0.Rd Rprof.out Rplots.*
 
 test-Packages:
 	@for p in $(R_PKGS_BASE); do \
@@ -205,36 +212,54 @@ test-all-extras: Makefile
 	@for name in $(all-extra-tests); do \
 	  $(MAKE) test-$${name} || exit 1; \
 	done
+
 test-Demo:
 	@echo "running demos from base and eda"
 	@$(MAKE) $(test-out-demo) RVAL_IF_DIFF=0
+
+## These depend on an internet connection, and the sites being up
+## So allow this to fail: it may be slow doing so.
 test-Internet:
 	@echo "running tests of Internet and socket functions"
-	@$(MAKE) $(test-out-internet) RVAL_IF_DIFF=0
+	-@$(MAKE) $(test-out-internet) RVAL_IF_DIFF=0
+
+test-IsAs:
+	@echo "running tests of consistency of as/is.*"
+	@$(MAKE) $(test-out-isas) RVAL_IF_DIFF=1
+
 test-Lapack:
 	@echo "running tests of LAPACK-based functions"
 	@$(MAKE) $(test-out-lapack) RVAL_IF_DIFF=0
+
 test-Nafns:
 	@echo "running tests of NA handling functions"
 	@$(MAKE) $(test-out-nafns) RVAL_IF_DIFF=0
+
 test-Postscript:
 	@echo "running tests of postscript() families"
 	@$(MAKE) $(test-out-postscript) RVAL_IF_DIFF=0
+
 test-Random:
 	@echo "running tests of random deviate generation"
 	@$(MAKE) $(test-out-random) RVAL_IF_DIFF=1
+
 test-Reg:
 	@echo "running regression tests"
 	@$(MAKE) $(test-out-reg) RVAL_IF_DIFF=0
+
 test-Segfault:
 	@echo "running tests to possibly trigger segfaults"
 	@$(MAKE) $(test-out-segfault) RVAL_IF_DIFF=0
+	@rm -f data dumpdata.R F.Rd c0.Rd df0.Rd l0.Rd m0.Rd Rprof.out Rplots.*
+
+## note: not all platforms can build standalone, so allowed to fail.
+test-Standalone:
+	@echo "testing building standalone Rmath"
+	-@(cd $(top_builddir)/src/nmath/standalone; $(MAKE) check)
+
 test-Ts:
 	@echo "running tests of package ts functions"
 	@$(MAKE) $(test-out-ts) RVAL_IF_DIFF=0
-test-Standalone:
-	@echo "testing building standalone Rmath"
-	@(cd $(top_builddir)/src/nmath/standalone; $(MAKE) check)
 
 test-DocArgs:
 	@echo "checking whether arguments from usage are documented"
