Also use for printing hardcopy via latex and dvips. If first arg is `INDEX', then do index lookup on the remaining args as before. If first arg is `PRINT', do hardcopy.
git-svn-id: https://svn.r-project.org/R/branches/R-0-62-patches@1771 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/cmd/help b/cmd/help
--- a/cmd/help
+++ b/cmd/help
@@ -2,18 +2,37 @@
 #
 # ${RHOME}/cmd/help
 
-subject=${1}
-shift
-for index in $*
-do
-    if [ -f ${index} ];
-    then
-	file=`grep "^${subject}	" ${index} | cut -f 2`
-	if test -n "${file}"
+if [ "${1}" = "INDEX" ];
+then
+    subject=${2}
+    shift 2
+    for index in $*
+    do
+	if [ -f ${index} ];
 	then
-	    echo `dirname ${index}`/${file}
-	    exit 0
+	    file=`grep "^${subject}	" ${index} | cut -f 2`
+	    if test -n "${file}"
+	    then
+		echo `dirname ${index}`/${file}
+		exit 0
+	    fi
 	fi
+    done    
+    echo
+elif [ "${1}" = "PRINT" ];
+then
+    if [ "${LATEX}" = "false" ];
+    then
+	echo "Cannot print, latex seems to be unavailable"
+	exit 1
     fi
-done    
-echo
+    if [ "${DVIPS}" = "false" ];
+    then
+	echo "Cannot print, dvips seems to be unavailable"
+	exit 2
+    fi
+    shift
+    cd `dirname ${1}`
+    ${LATEX} ${1} >/dev/null 2>&1
+    ${DVIPS} ${1} -o "|${2}" 2>/dev/null
+fi
