tweak r88109
git-svn-id: https://svn.r-project.org/R/trunk@88110 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/po/Makefile.in b/po/Makefile.in
--- a/po/Makefile.in
+++ b/po/Makefile.in
@@ -58,8 +58,8 @@ update-RGui:
 
 ## en@quot has to be done in a UTF-8 locale
 update-pkg-po:
-	@for pkg in $(R_PKGS_PO); do \
-	   $(ECHO) "updating translations for $${pkg}"; \
-	   $(ECHO) "options(warn=2); tools:::update_pkg_po(\"$(top_srcdir)/src/library/$${pkg}\", mergeOpts=\"--no-wrap\")" | \
-	     R_DEFAULT_PACKAGES=NULL LC_COLLATE=C $(R_EXE) || exit 1; \
-	done
+	@fail=; for pkg in $(R_PKGS_PO); do \
+	  $(ECHO); $(ECHO) "updating translations for $${pkg}"; \
+	  $(ECHO) "options(warn=2); tools:::update_pkg_po(\"$(top_srcdir)/src/library/$${pkg}\", mergeOpts=\"--no-wrap\")" | \
+	    R_DEFAULT_PACKAGES=NULL LC_COLLATE=C $(R_EXE) || fail="$${fail} $${pkg}"; \
+	done; if test -n "$${fail}"; then $(ECHO) "FAILED:$${fail}"; exit 1; fi
