Updated from autoconf CVS.
git-svn-id: https://svn.r-project.org/R/branches/R-1-3-patches@15140 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/tools/missing b/tools/missing
--- a/tools/missing
+++ b/tools/missing
@@ -18,6 +18,11 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 # 02111-1307, USA.
 
+# As a special exception to the GNU General Public License, if you
+# distribute this file as part of a program that contains a
+# configuration script generated by Autoconf, you may include it under
+# the same distribution terms that you use for the rest of that program.
+
 if test $# -eq 0; then
   echo 1>&2 "Try \`$0 --help' for more information"
   exit 1
@@ -25,6 +30,8 @@ fi
 
 run=:
 
+# In the cases where this matters, `missing' is being run in the
+# srcdir already.
 if test -f configure.ac; then
   configure_ac=configure.ac
 else
@@ -202,6 +209,11 @@ WARNING: \`$1' is missing on your system.  You should only need it if
     ;;
 
   makeinfo)
+    if test -z "$run" && (makeinfo --version > /dev/null 2>&1); then
+       # We have makeinfo, but it failed.
+       exit 1
+    fi
+
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
          you modified a \`.texi' or \`.texinfo' file, or any other file
