branch update
git-svn-id: https://svn.r-project.org/R/trunk@21675 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/tools/rsync-recommended b/tools/rsync-recommended
--- a/tools/rsync-recommended
+++ b/tools/rsync-recommended
@@ -28,13 +28,14 @@ fi
     --exclude=Makefile.in --exclude=Makefile --exclude=.cvsignore \
     --include=*.tar.gz --exclude=*.tgz \
     "${CRAN_RSYNC}"/src/contrib/${version}/Recommended/ . || \
-    echo "*** rsync failed to update Recommended files ***" && exit 1
+    (echo "*** rsync failed to update Recommended files ***" && exit 1)
 
   ## Link each package to a simplified name so that Make has an easier
   ## time.  Notice that as far as Make is concerned, the symlinks have
   ## the same timestamp as the file they point to.  Don't remove the 
   ## existing links until now in case rsync fails.
 
+  echo "Creating links"
   rm -f *.tgz
   for i in ${PKGS} ; do
     ln -s $i*.tar.gz ${i}.tgz
