Require texi2dvi (part of texinfo) to make manuals when installing R. Fall back to R code for making vignettes if not present.
git-svn-id: https://svn.r-project.org/R/trunk@42539 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -74,6 +74,10 @@ docs: html
 	  echo "ERROR: 'tex' needed but missing on your system."; \
 	  exit 1; \
 	fi
+	@if test "$(TEXI2DVI)" = false; then \
+	  echo "ERROR: 'texi2dvi' needed but missing on your system."; \
+	  exit 1; \
+	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2DVI) $<
 
 .texi.html:
@@ -95,6 +99,11 @@ docs: html
 .texi.pdf:
 	@if test "$(PDFTEX)" = false; then \
 	  echo "ERROR: 'pdftex' needed but missing on your system."; \
+	  exit 1; \
+	fi
+	fi
+	@if test "$(TEXI2DVI)" = false; then \
+	  echo "ERROR: 'texi2dvi' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2PDF) $<
