New file `resources.texi'. Add rules for creating `RESOURCES' and `resources.html' from this.
git-svn-id: https://svn.r-project.org/R/branches/R-1-2-patches@12052 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -17,6 +17,7 @@ DISTFILES = \
 	Makefile.in Makefile.win \
 	R-defs.texi dir texinfo.tex \
 	$(SOURCES_TEXI) \
+	resources.texi \
 	R-exts.R R-exts.c R-intro.R \
 	Rd.sty hyperref.cfg \
 	omsaer.fd omsaett.fd omscmtt.fd \
@@ -283,20 +284,35 @@ distclean: clean
 maintainer-clean: distclean
 
 MAKEINFO_TEXT_OPTS = --number-sections --fill-column=76 --no-split --no-headers
-MAKEINFO_HTML_OPTS = --number-sections --html
-maintainer-build: $(top_srcdir)/FAQ $(top_srcdir)/doc/html/faq.html
+maintainer-build: \
+  $(top_srcdir)/FAQ \
+  $(top_srcdir)/RESOURCES \
+  $(top_srcdir)/doc/html/faq.html \
+  $(top_srcdir)/doc/html/resources.html
 $(top_srcdir)/FAQ: $(srcdir)/R-FAQ.texi
 	@if test "$(MAKEINFO)" = false; then \
 	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	@$(MAKEINFO) $(MAKEINFO_TEXT_OPTS) $< -o $@
+	$(MAKEINFO) $(MAKEINFO_TEXT_OPTS) $< -o $@
 $(top_srcdir)/doc/html/faq.html: $(srcdir)/R-FAQ.texi
 	@if test "$(MAKEINFO)" = false; then \
 	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
 	  exit 1; \
 	fi
-	@$(MAKEINFO) $(MAKEINFO_HTML_OPTS) $< -o $@
+	$(MAKEINFO) --html --number-sections $< -o $@
+$(top_srcdir)/RESOURCES: $(srcdir)/resources.texi
+	@if test "$(MAKEINFO)" = false; then \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
+	  exit 1; \
+	fi
+	$(MAKEINFO) $(MAKEINFO_TEXT_OPTS) $< -o $@
+$(top_srcdir)/doc/html/resources.html: $(srcdir)/resources.texi
+	@if test "$(MAKEINFO)" = false; then \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
+	  exit 1; \
+	fi
+	$(MAKEINFO) --html --no-headers $< -o $@
 
 distdir: $(DISTFILES)
 	@for f in $(DISTFILES); do \
