maintainer-mode to make R-admin.html, tweak appearance
git-svn-id: https://svn.r-project.org/R/trunk@14185 00db46b3-68df-0310-9c12-caf00c1e9a41

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -286,7 +286,8 @@ maintainer-build: \
   $(top_srcdir)/FAQ \
   $(top_srcdir)/RESOURCES \
   $(top_srcdir)/doc/html/faq.html \
-  $(top_srcdir)/doc/html/resources.html
+  $(top_srcdir)/doc/html/resources.html \
+  $(top_srcdir)/doc/html/R-admin.html
 $(top_srcdir)/FAQ: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-FAQ.texi
 	@if test "$(MAKEINFO)" = false; then \
 	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
@@ -311,6 +312,12 @@ $(top_srcdir)/doc/html/resources.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/resource
 	  exit 1; \
 	fi
 	$(MAKEINFO) --html --no-headers $< -o $@
+$(top_srcdir)/doc/html/R-admin.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-admin.texi $(texiincludes)
+	@if test "$(MAKEINFO)" = false; then \
+	  echo "ERROR: \`makeinfo' v4 needed but missing on your system."; \
+	  exit 1; \
+	fi
+	$(MAKEINFO) --html --no-headers --number-sections -I$(srcdir) $< -o $@
 
 distdir: $(DISTFILES)
 	@for f in $(DISTFILES); do \
